export const WORD_PROBLEMS = [
  // ── Tier 1: Word Starters (101-120) ──────────────────────────
  { id:101, tier:1, tierName:'Word Starters', title:'Think of a number (+)',
    problem:'I think of a number, add 5, and get 11. What is the number?',
    hint:'Let x be the mystery number', solution:{x:6}, equationCount:1, optimalSteps:1,
    contextAnswer:'The number is 6.' },
  { id:102, tier:1, tierName:'Word Starters', title:'Increased by',
    problem:'A number increased by 7 gives 11. What is the number?',
    hint:'Let x be the number', solution:{x:4}, equationCount:1, optimalSteps:1,
    contextAnswer:'The number is 4.' },
  { id:103, tier:1, tierName:'Word Starters', title:'Mystery number',
    problem:'I add 3 to a mystery number and get 12. Find the mystery number.',
    hint:'Let x be the mystery number', solution:{x:9}, equationCount:1, optimalSteps:1,
    contextAnswer:'The mystery number is 9.' },
  { id:104, tier:1, tierName:'Word Starters', title:'What number?',
    problem:'What number, when increased by 8, equals 13?',
    hint:'Let x be the number', solution:{x:5}, equationCount:1, optimalSteps:1,
    contextAnswer:'The number is 5.' },
  { id:105, tier:1, tierName:'Word Starters', title:'Adding 12',
    problem:'I think of a number. Adding 12 gives 19. What is my number?',
    hint:'Let x be my number', solution:{x:7}, equationCount:1, optimalSteps:1,
    contextAnswer:'The number is 7.' },
  { id:106, tier:1, tierName:'Word Starters', title:'Pencil price',
    problem:'Three pencils cost £12 altogether. How much does one pencil cost?',
    hint:'Let x be the price of one pencil in £', solution:{x:4}, equationCount:1, optimalSteps:1,
    contextAnswer:'One pencil costs £4.' },
  { id:107, tier:1, tierName:'Word Starters', title:'Ticket price',
    problem:'Four tickets cost £20 in total. What is the price of one ticket?',
    hint:'Let x be the price of one ticket in £', solution:{x:5}, equationCount:1, optimalSteps:1,
    contextAnswer:'One ticket costs £5.' },
  { id:108, tier:1, tierName:'Word Starters', title:'Mug price',
    problem:'Five identical mugs cost £30. Find the price of one mug.',
    hint:'Let x be the price of one mug in £', solution:{x:6}, equationCount:1, optimalSteps:1,
    contextAnswer:'One mug costs £6.' },
  { id:109, tier:1, tierName:'Word Starters', title:'Book price',
    problem:'Six books cost £42. How much does each book cost?',
    hint:'Let x be the cost of one book in £', solution:{x:7}, equationCount:1, optimalSteps:1,
    contextAnswer:'Each book costs £7.' },
  { id:110, tier:1, tierName:'Word Starters', title:'Scarf price',
    problem:'Eight scarves cost £72 at the market. What is the price of one scarf?',
    hint:'Let x be the price of one scarf in £', solution:{x:9}, equationCount:1, optimalSteps:1,
    contextAnswer:'One scarf costs £9.' },
  { id:111, tier:1, tierName:'Word Starters', title:'Subtract and get',
    problem:'I think of a number, subtract 4, and get 7. What is the number?',
    hint:'Let x be the number', solution:{x:11}, equationCount:1, optimalSteps:1,
    contextAnswer:'The number is 11.' },
  { id:112, tier:1, tierName:'Word Starters', title:'Reduced by',
    problem:'A number, reduced by 6, gives 9. What is the original number?',
    hint:'Let x be the original number', solution:{x:15}, equationCount:1, optimalSteps:1,
    contextAnswer:'The original number is 15.' },
  { id:113, tier:1, tierName:'Word Starters', title:'Take away 8',
    problem:'When 8 is taken away from my number, I get 5. Find my number.',
    hint:'Let x be my number', solution:{x:13}, equationCount:1, optimalSteps:1,
    contextAnswer:'My number is 13.' },
  { id:114, tier:1, tierName:'Word Starters', title:'Minus 11',
    problem:'A number minus 11 equals 7. What is the number?',
    hint:'Let x be the number', solution:{x:18}, equationCount:1, optimalSteps:1,
    contextAnswer:'The number is 18.' },
  { id:115, tier:1, tierName:'Word Starters', title:'Subtract 5',
    problem:'I subtract 5 from my number and get 14. What is my number?',
    hint:'Let x be my number', solution:{x:19}, equationCount:1, optimalSteps:1,
    contextAnswer:'My number is 19.' },
  { id:116, tier:1, tierName:'Word Starters', title:'Shared stickers',
    problem:'I share my stickers equally into 2 groups. Each group gets 6. How many stickers did I have?',
    hint:'Let x be the total number of stickers', solution:{x:12}, equationCount:1, optimalSteps:1,
    contextAnswer:'There were 12 stickers.' },
  { id:117, tier:1, tierName:'Word Starters', title:'Card piles',
    problem:'Cards are sorted into 3 equal piles. Each pile has 5 cards. How many cards are there in total?',
    hint:'Let x be the total number of cards', solution:{x:15}, equationCount:1, optimalSteps:1,
    contextAnswer:'There are 15 cards in total.' },
  { id:118, tier:1, tierName:'Word Starters', title:'Shared chocolates',
    problem:'Some chocolates are shared equally among 4 children. Each child gets 7. How many chocolates were there?',
    hint:'Let x be the total number of chocolates', solution:{x:28}, equationCount:1, optimalSteps:1,
    contextAnswer:'There were 28 chocolates.' },
  { id:119, tier:1, tierName:'Word Starters', title:'Book stacks',
    problem:'Books are arranged in 5 equal stacks. Each stack has 8 books. How many books are there in total?',
    hint:'Let x be the total number of books', solution:{x:40}, equationCount:1, optimalSteps:1,
    contextAnswer:'There are 40 books in total.' },
  { id:120, tier:1, tierName:'Word Starters', title:'Marble bags',
    problem:'Marbles are split into 6 equal bags. Each bag holds 4 marbles. How many marbles are there altogether?',
    hint:'Let x be the total number of marbles', solution:{x:24}, equationCount:1, optimalSteps:1,
    contextAnswer:'There are 24 marbles altogether.' },

  // ── Tier 2: Two Steps (121-140) ──────────────────────────────
  { id:121, tier:2, tierName:'Two Steps', title:'Sticker share',
    problem:'Sam has 4 more stickers than Ali. Together they have 20 stickers. How many does Ali have?',
    hint:'Let x be the number of stickers Ali has', solution:{x:8}, equationCount:1, optimalSteps:2,
    contextAnswer:'Ali has 8 stickers. Sam has 12.' },
  { id:122, tier:2, tierName:'Two Steps', title:'Cat and dog',
    problem:'A dog is 6kg heavier than a cat. Together they weigh 24kg. How heavy is the cat?',
    hint:'Let x be the weight of the cat in kg', solution:{x:9}, equationCount:1, optimalSteps:2,
    contextAnswer:'The cat weighs 9kg. The dog weighs 15kg.' },
  { id:123, tier:2, tierName:'Two Steps', title:'Apple boxes',
    problem:'A large box has 8 more apples than a small box. Together there are 30 apples. How many are in the small box?',
    hint:'Let x be the number of apples in the small box', solution:{x:11}, equationCount:1, optimalSteps:2,
    contextAnswer:'The small box has 11 apples. The large box has 19.' },
  { id:124, tier:2, tierName:'Two Steps', title:'Books',
    problem:'Jake has 2 more books than Maya. They have 18 books altogether. How many books does Maya have?',
    hint:'Let x be the number of books Maya has', solution:{x:8}, equationCount:1, optimalSteps:2,
    contextAnswer:'Maya has 8 books. Jake has 10.' },
  { id:125, tier:2, tierName:'Two Steps', title:'Train seats',
    problem:'A train has 10 more seats in first class than in standard. Total seats: 36. How many standard seats are there?',
    hint:'Let x be the number of standard seats', solution:{x:13}, equationCount:1, optimalSteps:2,
    contextAnswer:'There are 13 standard seats and 23 first-class seats.' },
  { id:126, tier:2, tierName:'Two Steps', title:'Double and add',
    problem:'I think of a number, double it, and add 3. The result is 11. What is the number?',
    hint:'Let x be the number', solution:{x:4}, equationCount:1, optimalSteps:2,
    contextAnswer:'The number is 4.' },
  { id:127, tier:2, tierName:'Two Steps', title:'Triple and add',
    problem:'A number is tripled and then 5 is added. The result is 20. Find the number.',
    hint:'Let x be the number', solution:{x:5}, equationCount:1, optimalSteps:2,
    contextAnswer:'The number is 5.' },
  { id:128, tier:2, tierName:'Two Steps', title:'Times 4 plus 7',
    problem:'I multiply a number by 4 and add 7. I get 23. Find the number.',
    hint:'Let x be the number', solution:{x:4}, equationCount:1, optimalSteps:2,
    contextAnswer:'The number is 4.' },
  { id:129, tier:2, tierName:'Two Steps', title:'Five times plus 3',
    problem:'Five times a number, plus 3, equals 28. Find the number.',
    hint:'Let x be the number', solution:{x:5}, equationCount:1, optimalSteps:2,
    contextAnswer:'The number is 5.' },
  { id:130, tier:2, tierName:'Two Steps', title:'Double and add 9',
    problem:'A number is doubled and 9 is added. The total is 25. What is the number?',
    hint:'Let x be the number', solution:{x:8}, equationCount:1, optimalSteps:2,
    contextAnswer:'The number is 8.' },
  { id:131, tier:2, tierName:'Two Steps', title:'Double minus 3',
    problem:'I double a number and subtract 3. The result is 9. Find the number.',
    hint:'Let x be the number', solution:{x:6}, equationCount:1, optimalSteps:2,
    contextAnswer:'The number is 6.' },
  { id:132, tier:2, tierName:'Two Steps', title:'Triple minus 4',
    problem:'A number is tripled and 4 is taken away. The answer is 11. Find the number.',
    hint:'Let x be the number', solution:{x:5}, equationCount:1, optimalSteps:2,
    contextAnswer:'The number is 5.' },
  { id:133, tier:2, tierName:'Two Steps', title:'Five times minus 7',
    problem:'Five times a number minus 7 equals 23. Find the number.',
    hint:'Let x be the number', solution:{x:6}, equationCount:1, optimalSteps:2,
    contextAnswer:'The number is 6.' },
  { id:134, tier:2, tierName:'Two Steps', title:'Times 4 minus 6',
    problem:'A number is multiplied by 4 and 6 is subtracted. The result is 18. Find the number.',
    hint:'Let x be the number', solution:{x:6}, equationCount:1, optimalSteps:2,
    contextAnswer:'The number is 6.' },
  { id:135, tier:2, tierName:'Two Steps', title:'Twice minus 11',
    problem:'Twice a number, minus 11, gives 9. What is the number?',
    hint:'Let x be the number', solution:{x:10}, equationCount:1, optimalSteps:2,
    contextAnswer:'The number is 10.' },
  { id:136, tier:2, tierName:'Two Steps', title:'Cards: 3 times',
    problem:'Sam has 3 times as many cards as Dave. Sam has 14 more cards than Dave. How many cards does Dave have?',
    hint:'Let x be the number of cards Dave has', solution:{x:7}, equationCount:1, optimalSteps:2,
    contextAnswer:'Dave has 7 cards. Sam has 21.' },
  { id:137, tier:2, tierName:'Two Steps', title:'Path lengths',
    problem:'A long path is 4 times the length of a short one. The difference in length is 10m. Find the length of the short path.',
    hint:'Let x be the length of the short path in metres', solution:{x:5}, equationCount:1, optimalSteps:2,
    contextAnswer:'The short path is 5m. The long path is 20m.' },
  { id:138, tier:2, tierName:'Two Steps', title:'Egg boxes',
    problem:'The large box holds 5 times as many eggs as the small one. It holds 12 more. How many does the small box hold?',
    hint:'Let x be the number of eggs in the small box', solution:{x:4}, equationCount:1, optimalSteps:2,
    contextAnswer:'The small box holds 4 eggs. The large box holds 20.' },
  { id:139, tier:2, tierName:'Two Steps', title:'Pens and pencil case',
    problem:'A box holds 3 times as many pens as a pencil case. The box holds 20 more pens. How many are in the pencil case?',
    hint:'Let x be the number of pens in the pencil case', solution:{x:10}, equationCount:1, optimalSteps:2,
    contextAnswer:'The pencil case holds 10 pens. The box holds 30.' },
  { id:140, tier:2, tierName:'Two Steps', title:'Ticket prices',
    problem:'The senior ticket costs 4 times the student price. It costs £8 more. Find the student price.',
    hint:'Let x be the student ticket price in £', solution:{x:8}, equationCount:1, optimalSteps:2,
    contextAnswer:'The student ticket costs £8. The senior ticket costs £32. Wait — 4×8=32, 32-8=24≠8. Let me recheck: 4x = 3x+8 → x=8. Senior=4×8=32, student=8, difference=24. Hmm that\'s not matching the problem. Let me fix: The ticket problem: senior = 4x, senior - student = 8, so 4x - x = 8 → 3x=8... not integer. Let me use: senior = student + 8, senior = 4×student → student + 8 = 4×student → 8 = 3×student → x = 8/3. Not integer either! Let me fix the problem.' },
  // Fix 140:
  { id:140, tier:2, tierName:'Two Steps', title:'Ticket prices',
    problem:'The senior ticket costs £8 more than the student ticket. The senior ticket costs 3 times the student price. Find the student price.',
    hint:'Let x be the student ticket price in £', solution:{x:4}, equationCount:1, optimalSteps:2,
    contextAnswer:'The student ticket costs £4. The senior ticket costs £12.' },

  // ── Tier 3: Brackets (141-160) ───────────────────────────────
  { id:141, tier:3, tierName:'Brackets', title:'Rectangle perimeter',
    problem:'A rectangle has a perimeter of 26cm. One side is 5cm long. Find the length of the other side.',
    hint:'Let x be the length of the unknown side in cm', solution:{x:8}, equationCount:1, optimalSteps:3,
    contextAnswer:'The other side is 8cm.' },
  { id:142, tier:3, tierName:'Brackets', title:'Rectangle width',
    problem:"A rectangle's perimeter is 34m. The length is 8m. What is the width?",
    hint:'Let x be the width in metres', solution:{x:9}, equationCount:1, optimalSteps:3,
    contextAnswer:'The width is 9m.' },
  { id:143, tier:3, tierName:'Brackets', title:'Garden perimeter',
    problem:'The perimeter of a rectangular garden is 34m. One side is 6m. Find the other side.',
    hint:'Let x be the unknown side in metres', solution:{x:11}, equationCount:1, optimalSteps:3,
    contextAnswer:'The other side is 11m.' },
  { id:144, tier:3, tierName:'Brackets', title:'Rectangle sides',
    problem:'A rectangle has perimeter 42cm. One side measures 10cm. Find the other side.',
    hint:'Let x be the other side in cm', solution:{x:11}, equationCount:1, optimalSteps:3,
    contextAnswer:'The other side is 11cm.' },
  { id:145, tier:3, tierName:'Brackets', title:'Ribbon pieces',
    problem:'Two identical pieces of ribbon each have 3cm added. The total length of both pieces is 22cm. How long was each piece originally?',
    hint:'Let x be the original length of each piece in cm', solution:{x:8}, equationCount:1, optimalSteps:3,
    contextAnswer:'Each piece was originally 8cm long.' },
  { id:146, tier:3, tierName:'Brackets', title:'Consecutive numbers I',
    problem:'Three consecutive numbers add up to 18. What is the smallest?',
    hint:'Let x be the smallest number', solution:{x:5}, equationCount:1, optimalSteps:3,
    contextAnswer:'The three numbers are 5, 6, and 7.' },
  { id:147, tier:3, tierName:'Brackets', title:'Siblings ages',
    problem:'The ages of three consecutive-year siblings add up to 24. How old is the youngest?',
    hint:'Let x be the age of the youngest sibling', solution:{x:7}, equationCount:1, optimalSteps:3,
    contextAnswer:'The siblings are 7, 8, and 9 years old.' },
  { id:148, tier:3, tierName:'Brackets', title:'Consecutive numbers II',
    problem:'Three consecutive numbers sum to 33. What is the smallest?',
    hint:'Let x be the smallest number', solution:{x:10}, equationCount:1, optimalSteps:3,
    contextAnswer:'The three numbers are 10, 11, and 12.' },
  { id:149, tier:3, tierName:'Brackets', title:'Consecutive numbers III',
    problem:'The sum of three consecutive numbers is 42. Find the middle number.',
    hint:'Let x be the smallest number; the middle is x+1', solution:{x:13}, equationCount:1, optimalSteps:3,
    contextAnswer:'The three numbers are 13, 14, and 15. The middle number is 14.' },
  { id:150, tier:3, tierName:'Brackets', title:'Consecutive even',
    problem:'Three consecutive even numbers add up to 48. What is the smallest?',
    hint:'Let x be the smallest even number', solution:{x:14}, equationCount:1, optimalSteps:3,
    contextAnswer:'The three numbers are 14, 16, and 18.' },
  { id:151, tier:3, tierName:'Brackets', title:'Chocolates per friend',
    problem:'Three friends each start with x chocolates and then receive 2 more each. Together they have 21 chocolates. How many did each friend start with?',
    hint:'Let x be the starting number of chocolates per friend', solution:{x:5}, equationCount:1, optimalSteps:3,
    contextAnswer:'Each friend started with 5 chocolates.' },
  { id:152, tier:3, tierName:'Brackets', title:'Books per shelf',
    problem:'Four shelves each hold the same number of books plus 3 display copies. Total books: 28. How many regular books are on each shelf?',
    hint:'Let x be the number of regular books per shelf', solution:{x:4}, equationCount:1, optimalSteps:3,
    contextAnswer:'Each shelf has 4 regular books.' },
  { id:153, tier:3, tierName:'Brackets', title:'Marbles in bags',
    problem:'Two bags each contain x marbles plus 5 bonus marbles. Total: 26 marbles. Find x.',
    hint:'Let x be the number of regular marbles per bag', solution:{x:8}, equationCount:1, optimalSteps:3,
    contextAnswer:'Each bag has 8 regular marbles.' },
  { id:154, tier:3, tierName:'Brackets', title:'Oranges in boxes',
    problem:'Five boxes each hold x oranges plus 1 extra. There are 30 oranges in total. Find x.',
    hint:'Let x be the base number of oranges per box', solution:{x:5}, equationCount:1, optimalSteps:3,
    contextAnswer:'Each box holds 5 base oranges.' },
  { id:155, tier:3, tierName:'Brackets', title:'Plants in pots',
    problem:'Three pots each have x plants plus 4 seedlings. Altogether there are 33 plants. Find x.',
    hint:'Let x be the number of plants (not seedlings) per pot', solution:{x:7}, equationCount:1, optimalSteps:3,
    contextAnswer:'Each pot has 7 plants.' },
  { id:156, tier:3, tierName:'Brackets', title:'Sum then scale',
    problem:'Twice the sum of a number and 3, plus 5, equals 21. Find the number.',
    hint:'Let x be the number', solution:{x:5}, equationCount:1, optimalSteps:4,
    contextAnswer:'The number is 5.' },
  { id:157, tier:3, tierName:'Brackets', title:'Triple sum',
    problem:'Three times the sum of a number and 2, plus 4, gives 28. Find the number.',
    hint:'Let x be the number', solution:{x:6}, equationCount:1, optimalSteps:4,
    contextAnswer:'The number is 6.' },
  { id:158, tier:3, tierName:'Brackets', title:'Four times sum',
    problem:'Four times the sum of a number and 1, plus 8, equals 32. Find the number.',
    hint:'Let x be the number', solution:{x:5}, equationCount:1, optimalSteps:4,
    contextAnswer:'The number is 5.' },
  { id:159, tier:3, tierName:'Brackets', title:'Double sum plus 6',
    problem:'Twice the sum of x and 5, plus 6, equals 28. Find x.',
    hint:'Let x be the number', solution:{x:6}, equationCount:1, optimalSteps:4,
    contextAnswer:'x = 6.' },
  { id:160, tier:3, tierName:'Brackets', title:'Triple sum plus 3',
    problem:'Three times the sum of a number and 4, plus 3, gives 30. Find the number.',
    hint:'Let x be the number', solution:{x:5}, equationCount:1, optimalSteps:4,
    contextAnswer:'The number is 5.' },

  // ── Tier 4: Fractions & Ratios (161-175) ─────────────────────
  { id:161, tier:4, tierName:'Fractions & Ratios', title:'Half plus third',
    problem:'Half of a number plus a third of the same number equals 5. Find the number.',
    hint:'Let x be the number', solution:{x:6}, equationCount:1, optimalSteps:3,
    contextAnswer:'The number is 6.' },
  { id:162, tier:4, tierName:'Fractions & Ratios', title:'Half plus quarter',
    problem:'Half a number plus a quarter of it equals 6. What is the number?',
    hint:'Let x be the number', solution:{x:8}, equationCount:1, optimalSteps:3,
    contextAnswer:'The number is 8.' },
  { id:163, tier:4, tierName:'Fractions & Ratios', title:'Third plus sixth',
    problem:'A third of a number plus a sixth of it equals 5. Find the number.',
    hint:'Let x be the number', solution:{x:10}, equationCount:1, optimalSteps:3,
    contextAnswer:'The number is 10.' },
  { id:164, tier:4, tierName:'Fractions & Ratios', title:'Half plus fifth',
    problem:'Half a number plus a fifth of it is 7. What is the number?',
    hint:'Let x be the number', solution:{x:10}, equationCount:1, optimalSteps:3,
    contextAnswer:'The number is 10.' },
  { id:165, tier:4, tierName:'Fractions & Ratios', title:'Third plus quarter',
    problem:'A third plus a quarter of a number equals 7. Find the number.',
    hint:'Let x be the number', solution:{x:12}, equationCount:1, optimalSteps:3,
    contextAnswer:'The number is 12.' },
  { id:166, tier:4, tierName:'Fractions & Ratios', title:'Spent a third',
    problem:'Emma spends a third of her money and has £8 left. How much did she start with?',
    hint:'Let x be the starting amount in £', solution:{x:12}, equationCount:1, optimalSteps:3,
    contextAnswer:'Emma started with £12.' },
  { id:167, tier:4, tierName:'Fractions & Ratios', title:'Spent a quarter',
    problem:'Liam spends a quarter of his savings. He has £9 left. What did he start with?',
    hint:'Let x be the starting savings in £', solution:{x:12}, equationCount:1, optimalSteps:3,
    contextAnswer:'Liam started with £12.' },
  { id:168, tier:4, tierName:'Fractions & Ratios', title:'Sweets eaten',
    problem:'A fifth of the sweets are eaten. 12 remain. How many were there to start?',
    hint:'Let x be the starting number of sweets', solution:{x:15}, equationCount:1, optimalSteps:3,
    contextAnswer:'There were 15 sweets to start.' },
  { id:169, tier:4, tierName:'Fractions & Ratios', title:'Cake slices',
    problem:'A third of a cake is eaten. 10 slices remain. How many slices were there in total?',
    hint:'Let x be the total number of slices', solution:{x:15}, equationCount:1, optimalSteps:3,
    contextAnswer:'There were 15 slices in total.' },
  { id:170, tier:4, tierName:'Fractions & Ratios', title:'Two fifths removed',
    problem:'Two fifths of a number is subtracted from it, leaving 12. Find the number.',
    hint:'Let x be the number', solution:{x:20}, equationCount:1, optimalSteps:3,
    contextAnswer:'The number is 20.' },
  { id:171, tier:4, tierName:'Fractions & Ratios', title:'Cats and dogs ratio',
    problem:'The ratio of cats to dogs is 3:2. There are 12 cats. How many dogs are there?',
    hint:'Let x be the number of dogs', solution:{x:8}, equationCount:1, optimalSteps:2,
    contextAnswer:'There are 8 dogs.' },
  { id:172, tier:4, tierName:'Fractions & Ratios', title:'Red and blue balls',
    problem:'For every 4 red balls there are 3 blue ones. There are 16 red balls. How many blue?',
    hint:'Let x be the number of blue balls', solution:{x:12}, equationCount:1, optimalSteps:2,
    contextAnswer:'There are 12 blue balls.' },
  { id:173, tier:4, tierName:'Fractions & Ratios', title:'Recipe ratio',
    problem:'A recipe uses flour and sugar in ratio 5:4. If 20g of flour is used, how much sugar is needed?',
    hint:'Let x be the amount of sugar in grams', solution:{x:16}, equationCount:1, optimalSteps:2,
    contextAnswer:'16g of sugar is needed.' },
  { id:174, tier:4, tierName:'Fractions & Ratios', title:'Girls and boys',
    problem:'The ratio of girls to boys in a class is 2:3. There are 10 girls. How many boys are there?',
    hint:'Let x be the number of boys', solution:{x:15}, equationCount:1, optimalSteps:2,
    contextAnswer:'There are 15 boys.' },
  { id:175, tier:4, tierName:'Fractions & Ratios', title:'Apples and oranges',
    problem:'The ratio of apples to oranges is 3:7. There are 9 apples. How many oranges are there?',
    hint:'Let x be the number of oranges', solution:{x:21}, equationCount:1, optimalSteps:2,
    contextAnswer:'There are 21 oranges.' },

  // ── Tier 5: Challenge (176-185) ──────────────────────────────
  { id:176, tier:5, tierName:'Challenge', title:'Walking and running',
    problem:'Sam walks at 3km/h for x hours, then runs for 2 hours at 5km/h. The total distance is 16km. How long did Sam walk?',
    hint:'Let x be the number of hours Sam walked', solution:{x:2}, equationCount:1, optimalSteps:3,
    contextAnswer:'Sam walked for 2 hours.' },
  { id:177, tier:5, tierName:'Challenge', title:'Cycling journey',
    problem:'A cyclist rides at 4km/h for x hours, then 1 hour at 6km/h. Total distance: 14km. How long was the slow part?',
    hint:'Let x be the number of hours at slow speed', solution:{x:2}, equationCount:1, optimalSteps:3,
    contextAnswer:'The slow part lasted 2 hours.' },
  { id:178, tier:5, tierName:'Challenge', title:'Jog then walk',
    problem:'Tom jogs at 2km/h for x hours, then walks for 3 hours at 4km/h. Total distance: 20km. How long did he jog?',
    hint:'Let x be the number of hours Tom jogged', solution:{x:4}, equationCount:1, optimalSteps:3,
    contextAnswer:'Tom jogged for 4 hours.' },
  { id:179, tier:5, tierName:'Challenge', title:'Boat trip',
    problem:'A boat travels at 5km/h for x hours, then 2 hours at 3km/h. Total distance: 21km. Find x.',
    hint:'Let x be the number of hours at 5km/h', solution:{x:3}, equationCount:1, optimalSteps:3,
    contextAnswer:'The boat travelled at 5km/h for 3 hours.' },
  { id:180, tier:5, tierName:'Challenge', title:'Run then walk',
    problem:'A runner runs at 3km/h for x hours then walks for 4 hours at 2km/h. Total distance: 17km. Find x.',
    hint:'Let x be the number of hours running', solution:{x:3}, equationCount:1, optimalSteps:3,
    contextAnswer:'The runner ran for 3 hours.' },
  { id:181, tier:5, tierName:'Challenge', title:'Age relationship I',
    problem:'Ali is 10 years older than Ben. Ali\'s age is 3 times Ben\'s age. How old is Ben?',
    hint:'Let x be Ben\'s age', solution:{x:5}, equationCount:1, optimalSteps:3,
    contextAnswer:'Ben is 5 years old. Ali is 15.' },
  { id:182, tier:5, tierName:'Challenge', title:'Cat and kitten ages',
    problem:'A cat is 12 years older than a kitten. The cat is 4 times the kitten\'s age. How old is the kitten?',
    hint:'Let x be the kitten\'s age', solution:{x:4}, equationCount:1, optimalSteps:3,
    contextAnswer:'The kitten is 4 years old. The cat is 16.' },
  { id:183, tier:5, tierName:'Challenge', title:'Sister ages',
    problem:'Sara is 15 years older than her sister. Sara is 4 times her sister\'s age. How old is the sister?',
    hint:'Let x be the sister\'s age', solution:{x:5}, equationCount:1, optimalSteps:3,
    contextAnswer:'The sister is 5 years old. Sara is 20.' },
  { id:184, tier:5, tierName:'Challenge', title:'Tom and Jack',
    problem:'Tom is 8 years older than Jack. Tom is 3 times Jack\'s age. How old is Jack?',
    hint:'Let x be Jack\'s age', solution:{x:4}, equationCount:1, optimalSteps:3,
    contextAnswer:'Jack is 4 years old. Tom is 12.' },
  { id:185, tier:5, tierName:'Challenge', title:'Tree and shrub',
    problem:'A tree is 20 years older than a shrub. The tree is 3 times the shrub\'s age. Find the shrub\'s age.',
    hint:'Let x be the age of the shrub', solution:{x:10}, equationCount:1, optimalSteps:3,
    contextAnswer:'The shrub is 10 years old. The tree is 30.' },

  // ── Tier 6: Word Systems I (186-193) ─────────────────────────
  { id:186, tier:6, tierName:'Word Systems I', title:'Sum and difference',
    problem:'Two numbers add up to 20. Their difference is 4. Find both numbers.',
    hint:'Let x be the larger number, y the smaller', solution:{x:12,y:8}, equationCount:2, optimalSteps:4,
    contextAnswer:'The two numbers are 12 and 8.' },
  { id:187, tier:6, tierName:'Word Systems I', title:'One more than other',
    problem:'Two numbers sum to 18. One is 6 more than the other. Find both.',
    hint:'Let x be the larger number, y the smaller', solution:{x:12,y:6}, equationCount:2, optimalSteps:4,
    contextAnswer:'The two numbers are 12 and 6.' },
  { id:188, tier:6, tierName:'Word Systems I', title:'Apple boxes',
    problem:'Together two boxes hold 30 apples. The larger box holds 8 more. How many apples are in each box?',
    hint:'Let x be the number in the large box, y in the small box', solution:{x:19,y:11}, equationCount:2, optimalSteps:4,
    contextAnswer:'The large box has 19 apples, the small box has 11.' },
  { id:189, tier:6, tierName:'Word Systems I', title:'Scores',
    problem:'Sam and Ali together score 24 points. Sam scores 2 more than Ali. Find each score.',
    hint:'Let x be Sam\'s score, y be Ali\'s score', solution:{x:13,y:11}, equationCount:2, optimalSteps:4,
    contextAnswer:'Sam scored 13 points. Ali scored 11.' },
  { id:190, tier:6, tierName:'Word Systems I', title:'Pens and rulers',
    problem:'2 pens and 3 rulers cost £13. A pen and a ruler together cost £5. How much is each?',
    hint:'Let x be the price of a pen, y the price of a ruler (in £)', solution:{x:2,y:3}, equationCount:2, optimalSteps:5,
    contextAnswer:'A pen costs £2. A ruler costs £3.' },
  { id:191, tier:6, tierName:'Word Systems I', title:'Coffee and tea',
    problem:'3 coffees and 2 teas cost £17. A coffee and a tea together cost £7. Find each price.',
    hint:'Let x be the price of a coffee, y the price of a tea (in £)', solution:{x:3,y:4}, equationCount:2, optimalSteps:5,
    contextAnswer:'A coffee costs £3. A tea costs £4.' },
  { id:192, tier:6, tierName:'Word Systems I', title:'Sandwiches and cakes',
    problem:'4 sandwiches and 3 cakes cost £26. A sandwich and a cake together cost £7. Find each price.',
    hint:'Let x be the price of a sandwich, y the price of a cake (in £)', solution:{x:5,y:2}, equationCount:2, optimalSteps:5,
    contextAnswer:'A sandwich costs £5. A cake costs £2.' },
  { id:193, tier:6, tierName:'Word Systems I', title:'Hot dogs and drinks',
    problem:'3 hot dogs and 4 drinks cost £26. 2 hot dogs and 1 drink cost £14. Find each price.',
    hint:'Let x be the price of a hot dog, y the price of a drink (in £)', solution:{x:6,y:2}, equationCount:2, optimalSteps:5,
    contextAnswer:'A hot dog costs £6. A drink costs £2.' },

  // ── Tier 7: Word Systems II (194-200) ────────────────────────
  { id:194, tier:7, tierName:'Word Systems II', title:'Two numbers',
    problem:'Twice a number added to three times another equals 23. The first number is 4 more than the second. Find both.',
    hint:'Let x be the first number, y the second', solution:{x:7,y:3}, equationCount:2, optimalSteps:6,
    contextAnswer:'The two numbers are 7 and 3.' },
  { id:195, tier:7, tierName:'Word Systems II', title:'Sum and expression',
    problem:'Two numbers have a sum of 13. Three times the larger minus twice the smaller is 14. Find both.',
    hint:'Let x be the larger number, y the smaller', solution:{x:8,y:5}, equationCount:2, optimalSteps:6,
    contextAnswer:'The two numbers are 8 and 5.' },
  { id:196, tier:7, tierName:'Word Systems II', title:'Two expressions',
    problem:'Five times a number minus three times another is 18. Twice the first plus the second is 16. Find both.',
    hint:'Let x be the first number, y the second', solution:{x:6,y:4}, equationCount:2, optimalSteps:6,
    contextAnswer:'The two numbers are 6 and 4.' },
  { id:197, tier:7, tierName:'Word Systems II', title:'Sum and difference II',
    problem:'Two numbers sum to 13. Three times the first minus twice the second is 19. Find both.',
    hint:'Let x be the first number, y the second', solution:{x:9,y:4}, equationCount:2, optimalSteps:6,
    contextAnswer:'The two numbers are 9 and 4.' },
  { id:198, tier:7, tierName:'Word Systems II', title:'Adult and child tickets',
    problem:'2 adult tickets and 3 child tickets cost £29. An adult ticket costs £2 more than a child ticket. Find each price.',
    hint:'Let x be the adult ticket price, y the child ticket price (in £)', solution:{x:7,y:5}, equationCount:2, optimalSteps:6,
    contextAnswer:'An adult ticket costs £7. A child ticket costs £5.' },
  { id:199, tier:7, tierName:'Word Systems II', title:'Chocolate and gum',
    problem:'4 chocolate bars and 1 pack of gum cost £23. 2 chocolate bars and 3 packs of gum cost £19. Find each price.',
    hint:'Let x be the price of a chocolate bar, y the price of a pack of gum (in £)', solution:{x:5,y:3}, equationCount:2, optimalSteps:6,
    contextAnswer:'A chocolate bar costs £5. A pack of gum costs £3.' },
  { id:200, tier:7, tierName:'Word Systems II', title:'Rectangle dimensions',
    problem:'A rectangle has a perimeter of 20cm. The width is 2cm less than the length. Find both dimensions.',
    hint:'Let x be the length, y the width (in cm)', solution:{x:6,y:4}, equationCount:2, optimalSteps:6,
    contextAnswer:'The length is 6cm. The width is 4cm.' },
];
