export const WORD_PROBLEMS = [
  // ── Tier 1: Word Starters (101-120) ──────────────────────────
  { id:101, tier:1, tierName:'Word Starters', title:'Number plus its double',
    problem:'A number added to its own double makes 18. Find the number.',
    hint:'Let x be the number. "Its double" is 2x, so write x + 2x = 18', solution:{x:6}, equationCount:1, optimalSteps:2,
    contextAnswer:'The number is 6.' },
  { id:102, tier:1, tierName:'Word Starters', title:'Adding gives double',
    problem:'I add 7 to a number and the result is exactly twice the number. What is the number?',
    hint:'Let x be the number. "Twice the number" is 2x, so x + 7 = 2x', solution:{x:7}, equationCount:1, optimalSteps:2,
    contextAnswer:'The number is 7.' },
  { id:103, tier:1, tierName:'Word Starters', title:'More than its half',
    problem:'A number is 5 more than its own half. Find the number.',
    hint:'Let x be the number. "Its half" is x/2, so x/2 + 5 = x', solution:{x:10}, equationCount:1, optimalSteps:2,
    contextAnswer:'The number is 10.' },
  { id:104, tier:1, tierName:'Word Starters', title:'Triple minus 5',
    problem:'I triple a number and subtract 5. The result equals double the number. Find the number.',
    hint:'Let x be the number. Triple is 3x, double is 2x, so 3x - 5 = 2x', solution:{x:5}, equationCount:1, optimalSteps:2,
    contextAnswer:'The number is 5.' },
  { id:105, tier:1, tierName:'Word Starters', title:'Plus 16 gives triple',
    problem:'A number plus 16 equals three times that number. Find the number.',
    hint:'Let x be the number. x + 16 = 3x', solution:{x:8}, equationCount:1, optimalSteps:2,
    contextAnswer:'The number is 8.' },
  { id:106, tier:1, tierName:'Word Starters', title:'Subtract from 30',
    problem:'I subtract a number from 30 and get twice the number. What is the number?',
    hint:'Let x be the number. 30 - x = 2x', solution:{x:10}, equationCount:1, optimalSteps:2,
    contextAnswer:'The number is 10.' },
  { id:107, tier:1, tierName:'Word Starters', title:'Four times minus 24',
    problem:'Four times a number, take away 24, equals the number itself. Find the number.',
    hint:'Let x be the number. 4x - 24 = x', solution:{x:8}, equationCount:1, optimalSteps:2,
    contextAnswer:'The number is 8.' },
  { id:108, tier:1, tierName:'Word Starters', title:'Number plus its triple',
    problem:'A number added to its own triple equals 28. Find the number.',
    hint:'Let x be the number. "Its triple" is 3x, so x + 3x = 28', solution:{x:7}, equationCount:1, optimalSteps:2,
    contextAnswer:'The number is 7.' },
  { id:109, tier:1, tierName:'Word Starters', title:'Double vs triple',
    problem:'I double a number and add 3. This gives the same result as trebling the number minus 5. Find the number.',
    hint:'Let x be the number. 2x + 3 = 3x - 5', solution:{x:8}, equationCount:1, optimalSteps:3,
    contextAnswer:'The number is 8.' },
  { id:110, tier:1, tierName:'Word Starters', title:'Five times vs twice',
    problem:'Five times a number, take away 6, equals twice the number plus 9. Find the number.',
    hint:'Let x be the number. 5x - 6 = 2x + 9', solution:{x:5}, equationCount:1, optimalSteps:3,
    contextAnswer:'The number is 5.' },
  { id:111, tier:1, tierName:'Word Starters', title:'Two related numbers',
    problem:'A number and 4 more than that number add up to 26. Find the smaller number.',
    hint:'Let x be the smaller number. The larger is x + 4, so x + (x + 4) = 26', solution:{x:11}, equationCount:1, optimalSteps:2,
    contextAnswer:'The smaller number is 11.' },
  { id:112, tier:1, tierName:'Word Starters', title:'Three in a row',
    problem:'Three consecutive whole numbers add up to 39. Find the smallest.',
    hint:'Let x be the smallest. The three numbers are x, x+1, x+2, so x + (x+1) + (x+2) = 39', solution:{x:12}, equationCount:1, optimalSteps:2,
    contextAnswer:'The smallest number is 12. The three numbers are 12, 13, and 14.' },
  { id:113, tier:1, tierName:'Word Starters', title:'Sum and gap',
    problem:'Two numbers add up to 44. The larger is 8 more than the smaller. Find the smaller number.',
    hint:'Let x be the smaller. The larger is x + 8, so x + (x + 8) = 44', solution:{x:18}, equationCount:1, optimalSteps:2,
    contextAnswer:'The smaller number is 18. The two numbers are 18 and 26.' },
  { id:114, tier:1, tierName:'Word Starters', title:'Subtract to get four times',
    problem:'I subtract a number from 55 and the result is 4 times the number. Find the number.',
    hint:'Let x be the number. 55 - x = 4x', solution:{x:11}, equationCount:1, optimalSteps:2,
    contextAnswer:'The number is 11.' },
  { id:115, tier:1, tierName:'Word Starters', title:'Plus 9 vs double minus 5',
    problem:'A number plus 9 equals double the number take away 5. Find the number.',
    hint:'Let x be the number. x + 9 = 2x - 5', solution:{x:14}, equationCount:1, optimalSteps:2,
    contextAnswer:'The number is 14.' },
  { id:116, tier:1, tierName:'Word Starters', title:'Half of 30',
    problem:'I subtract a number from 30. The result equals the number itself. Find the number.',
    hint:'Let x be the number. 30 - x = x', solution:{x:15}, equationCount:1, optimalSteps:2,
    contextAnswer:'The number is 15.' },
  { id:117, tier:1, tierName:'Word Starters', title:'Four times vs 60 minus',
    problem:'Four times a number equals 60 minus the number. Find the number.',
    hint:'Let x be the number. 4x = 60 - x', solution:{x:12}, equationCount:1, optimalSteps:2,
    contextAnswer:'The number is 12.' },
  { id:118, tier:1, tierName:'Word Starters', title:'More than two thirds',
    problem:'A number is 3 more than two thirds of itself. Find the number.',
    hint:'Let x be the number. Two thirds of x is 2x/3, so x = 2x/3 + 3', solution:{x:9}, equationCount:1, optimalSteps:3,
    contextAnswer:'The number is 9.' },
  { id:119, tier:1, tierName:'Word Starters', title:'Six times vs plus 30',
    problem:'Six times a number equals the number plus 30. Find the number.',
    hint:'Let x be the number. 6x = x + 30', solution:{x:6}, equationCount:1, optimalSteps:2,
    contextAnswer:'The number is 6.' },
  { id:120, tier:1, tierName:'Word Starters', title:'Double minus 7',
    problem:'I double a number and take away 7. The result equals the number plus 3. Find the number.',
    hint:'Let x be the number. 2x - 7 = x + 3', solution:{x:10}, equationCount:1, optimalSteps:2,
    contextAnswer:'The number is 10.' },

  // ── Tier 2: Two Steps (121-140) ──────────────────────────────
  { id:121, tier:2, tierName:'Two Steps', title:'Plumber call-out',
    problem:'A plumber charges a £35 call-out fee, then £22 per hour. The total bill is £101. How many hours did the plumber work?',
    hint:'Let x be the hours. The bill is: call-out + hours × rate = total, so 22x + 35 = 101',
    solution:{x:3}, equationCount:1, optimalSteps:2,
    contextAnswer:'The plumber worked 3 hours. Check: 35 + 22×3 = 35 + 66 = 101 ✓' },
  { id:122, tier:2, tierName:'Two Steps', title:'Gym membership',
    problem:'A gym charges a £40 joining fee, then £15 per month. After how many months will the total cost be £160?',
    hint:'Let x be the months. Joining fee + months × monthly rate = total, so 15x + 40 = 160',
    solution:{x:8}, equationCount:1, optimalSteps:2,
    contextAnswer:'After 8 months. Check: 40 + 15×8 = 40 + 120 = 160 ✓' },
  { id:123, tier:2, tierName:'Two Steps', title:'Phone plan',
    problem:'A phone plan has a £20 setup fee and costs £12 per month. After how many months will the total be £92?',
    hint:'Let x be the months. Setup fee + months × monthly cost = total, so 12x + 20 = 92',
    solution:{x:6}, equationCount:1, optimalSteps:2,
    contextAnswer:'After 6 months. Check: 20 + 12×6 = 20 + 72 = 92 ✓' },
  { id:124, tier:2, tierName:'Two Steps', title:'Taxi fare',
    problem:'A taxi charges £2 to start the meter, then £3 per mile. A journey costs £17. How many miles was the journey?',
    hint:'Let x be the miles. Flag-fall + miles × rate = total, so 3x + 2 = 17',
    solution:{x:5}, equationCount:1, optimalSteps:2,
    contextAnswer:'The journey was 5 miles. Check: 2 + 3×5 = 2 + 15 = 17 ✓' },
  { id:125, tier:2, tierName:'Two Steps', title:'Saving up',
    problem:'Maria already has £24 saved. She saves £8 per week. After how many weeks will she have £80?',
    hint:'Let x be the weeks. Current savings + weeks × weekly amount = target, so 8x + 24 = 80',
    solution:{x:7}, equationCount:1, optimalSteps:2,
    contextAnswer:'After 7 weeks. Check: 24 + 8×7 = 24 + 56 = 80 ✓' },
  { id:126, tier:2, tierName:'Two Steps', title:'Baker profit',
    problem:'A baker spends £8 per day on ingredients. Each loaf sells for £2. How many loaves must be sold to make a daily profit of £22?',
    hint:'Let x be the loaves sold. Profit = revenue − costs, so 2x − 8 = 22',
    solution:{x:15}, equationCount:1, optimalSteps:2,
    contextAnswer:'15 loaves. Check: 2×15 − 8 = 30 − 8 = 22 ✓' },
  { id:127, tier:2, tierName:'Two Steps', title:'Car hire',
    problem:'A car hire company charges a £50 booking fee plus £25 per day. A customer pays £250 total. How many days did they hire the car?',
    hint:'Let x be the days. Booking fee + days × daily rate = total, so 25x + 50 = 250',
    solution:{x:8}, equationCount:1, optimalSteps:2,
    contextAnswer:'8 days. Check: 50 + 25×8 = 50 + 200 = 250 ✓' },
  { id:128, tier:2, tierName:'Two Steps', title:'Magazine subscription',
    problem:'A magazine subscription costs £12 per month. You also paid a £36 joining fee upfront. After how many months will your total spend be £132?',
    hint:'Let x be the months. Joining fee + months × monthly cost = total, so 12x + 36 = 132',
    solution:{x:8}, equationCount:1, optimalSteps:2,
    contextAnswer:'After 8 months. Check: 36 + 12×8 = 36 + 96 = 132 ✓' },
  { id:129, tier:2, tierName:'Two Steps', title:'Football card rivalry',
    problem:'Ali has 4 times as many football cards as Ben. Ali has 21 more cards than Ben. How many cards does Ben have?',
    hint:'Let x be Ben\'s cards. Ali\'s count can be written two ways: 4x and x + 21. Set them equal: 4x = x + 21',
    solution:{x:7}, equationCount:1, optimalSteps:2,
    contextAnswer:'Ben has 7 cards, Ali has 28. Check: 28 = 4×7 ✓ and 28 − 7 = 21 ✓' },
  { id:130, tier:2, tierName:'Two Steps', title:'Age gap',
    problem:'Tom is 5 times as old as Sam. Tom is 16 years older than Sam. How old is Sam?',
    hint:'Let x be Sam\'s age. Tom\'s age is both 5x and x + 16. So 5x = x + 16',
    solution:{x:4}, equationCount:1, optimalSteps:2,
    contextAnswer:'Sam is 4, Tom is 20. Check: 20 = 5×4 ✓ and 20 − 4 = 16 ✓' },
  { id:131, tier:2, tierName:'Two Steps', title:'Train speeds',
    problem:'An express train travels at 3 times the speed of a local train. The express is 80 mph faster than the local. What is the speed of the local train?',
    hint:'Let x be the local speed in mph. Express speed is both 3x and x + 80. So 3x = x + 80',
    solution:{x:40}, equationCount:1, optimalSteps:2,
    contextAnswer:'Local: 40 mph, Express: 120 mph. Check: 120 = 3×40 ✓ and 120 − 40 = 80 ✓' },
  { id:132, tier:2, tierName:'Two Steps', title:'Fridge cooling',
    problem:'A fridge starts at 18°C and cools by 3°C every hour. After how many hours will the temperature reach −3°C?',
    hint:'Let x be the hours. Starting temp − cooling per hour × hours = final temp, so 18 − 3x = −3',
    solution:{x:7}, equationCount:1, optimalSteps:2,
    contextAnswer:'After 7 hours. Check: 18 − 3×7 = 18 − 21 = −3 ✓' },
  { id:133, tier:2, tierName:'Two Steps', title:'Quiz scoring',
    problem:'A quiz starts you on 40 points. Each wrong answer loses 2 points. A player finishes with 26 points. How many questions did they get wrong?',
    hint:'Let x be the wrong answers. Starting score − losses = final score, so 40 − 2x = 26',
    solution:{x:7}, equationCount:1, optimalSteps:2,
    contextAnswer:'7 wrong answers. Check: 40 − 2×7 = 40 − 14 = 26 ✓' },
  { id:134, tier:2, tierName:'Two Steps', title:'Electrician',
    problem:'An electrician charges a £30 call-out fee, then £45 per hour. The total invoice is £210. How many hours did the electrician work?',
    hint:'Let x be the hours. Call-out fee + hours × rate = total, so 45x + 30 = 210',
    solution:{x:4}, equationCount:1, optimalSteps:2,
    contextAnswer:'4 hours. Check: 30 + 45×4 = 30 + 180 = 210 ✓' },
  { id:135, tier:2, tierName:'Two Steps', title:'Sticker album',
    problem:'An album already has 16 stickers. Each pack adds 8 stickers. How many packs are needed to reach 80 stickers in total?',
    hint:'Let x be the packs. Current stickers + packs × per pack = target, so 8x + 16 = 80',
    solution:{x:8}, equationCount:1, optimalSteps:2,
    contextAnswer:'8 packs. Check: 16 + 8×8 = 16 + 64 = 80 ✓' },
  { id:136, tier:2, tierName:'Two Steps', title:'Online order',
    problem:'An online shop charges £5 for delivery plus £3 per item. An order costs £29 in total. How many items were ordered?',
    hint:'Let x be the items. Delivery + items × price per item = total, so 3x + 5 = 29',
    solution:{x:8}, equationCount:1, optimalSteps:2,
    contextAnswer:'8 items. Check: 5 + 3×8 = 5 + 24 = 29 ✓' },
  { id:137, tier:2, tierName:'Two Steps', title:'Cinema family',
    problem:'Cinema tickets cost £5 each for children and £9 for one adult. The family total is £29. How many children are there?',
    hint:'Let x be the children. Adult ticket + children × child ticket price = total, so 9 + 5x = 29',
    solution:{x:4}, equationCount:1, optimalSteps:2,
    contextAnswer:'4 children. Check: 9 + 5×4 = 9 + 20 = 29 ✓' },
  { id:138, tier:2, tierName:'Two Steps', title:'Bus journey',
    problem:'A bus waits 60 minutes at the terminus before departure, then takes 2 minutes per stop. The whole trip takes 180 minutes. How many stops does it make?',
    hint:'Let x be the stops. Waiting time + stops × minutes per stop = total time, so 2x + 60 = 180',
    solution:{x:60}, equationCount:1, optimalSteps:2,
    contextAnswer:'60 stops. Check: 60 + 2×60 = 60 + 120 = 180 ✓' },
  { id:139, tier:2, tierName:'Two Steps', title:'Farm animals',
    problem:'A farmer has some cows. He has 15 more sheep than cows. In total there are 31 animals. How many cows are there?',
    hint:'Let x be the cows. Sheep = x + 15. Total: x + (x + 15) = 31, which gives 2x + 15 = 31',
    solution:{x:8}, equationCount:1, optimalSteps:2,
    contextAnswer:'8 cows and 23 sheep. Check: 8 + 23 = 31 ✓ and 23 − 8 = 15 ✓' },
  { id:140, tier:2, tierName:'Two Steps', title:'Hotel stay',
    problem:'A hotel charges £80 per night plus a £25 booking fee. A guest pays £345 in total. For how many nights did they stay?',
    hint:'Let x be the nights. Booking fee + nights × nightly rate = total, so 80x + 25 = 345',
    solution:{x:4}, equationCount:1, optimalSteps:2,
    contextAnswer:'4 nights. Check: 25 + 80×4 = 25 + 320 = 345 ✓' },

  // ── Tier 3: Brackets (141-160) ───────────────────────────────
  { id:141, tier:3, tierName:'Brackets', title:'Rectangle perimeter',
    problem:'A rectangle has a perimeter of 26cm. One side is 5cm long. Find the length of the other side.',
    hint:'Let x be the length of the unknown side in cm', solution:{x:8}, equationCount:1, optimalSteps:3,
    contextAnswer:'The other side is 8cm.' },
  { id:142, tier:3, tierName:'Brackets', title:'Rectangle width',
    problem:"A rectangle's perimeter is 34m. The length is 8m. What is the width?",
    hint:'Let x be the width in metres', solution:{x:9}, equationCount:1, optimalSteps:3,
    contextAnswer:'The width is 9m.' },
  { id:143, tier:3, tierName:'Brackets', title:'Garden perimeter',
    problem:'The perimeter of a rectangular garden is 34m. One side is 6m. Find the other side.',
    hint:'Let x be the unknown side in metres', solution:{x:11}, equationCount:1, optimalSteps:3,
    contextAnswer:'The other side is 11m.' },
  { id:144, tier:3, tierName:'Brackets', title:'Rectangle sides',
    problem:'A rectangle has perimeter 42cm. One side measures 10cm. Find the other side.',
    hint:'Let x be the other side in cm', solution:{x:11}, equationCount:1, optimalSteps:3,
    contextAnswer:'The other side is 11cm.' },
  { id:145, tier:3, tierName:'Brackets', title:'Ribbon pieces',
    problem:'Two identical pieces of ribbon each have 3cm added. The total length of both pieces is 22cm. How long was each piece originally?',
    hint:'Let x be the original length of each piece in cm', solution:{x:8}, equationCount:1, optimalSteps:3,
    contextAnswer:'Each piece was originally 8cm long.' },
  { id:146, tier:3, tierName:'Brackets', title:'Consecutive numbers I',
    problem:'Three consecutive numbers add up to 18. What is the smallest?',
    hint:'Let x be the smallest number', solution:{x:5}, equationCount:1, optimalSteps:3,
    contextAnswer:'The three numbers are 5, 6, and 7.' },
  { id:147, tier:3, tierName:'Brackets', title:'Siblings ages',
    problem:'The ages of three consecutive-year siblings add up to 24. How old is the youngest?',
    hint:'Let x be the age of the youngest sibling', solution:{x:7}, equationCount:1, optimalSteps:3,
    contextAnswer:'The siblings are 7, 8, and 9 years old.' },
  { id:148, tier:3, tierName:'Brackets', title:'Consecutive numbers II',
    problem:'Three consecutive numbers sum to 33. What is the smallest?',
    hint:'Let x be the smallest number', solution:{x:10}, equationCount:1, optimalSteps:3,
    contextAnswer:'The three numbers are 10, 11, and 12.' },
  { id:149, tier:3, tierName:'Brackets', title:'Consecutive numbers III',
    problem:'The sum of three consecutive numbers is 42. Find the middle number.',
    hint:'Let x be the smallest number; the middle is x+1', solution:{x:13}, equationCount:1, optimalSteps:3,
    contextAnswer:'The three numbers are 13, 14, and 15. The middle number is 14.' },
  { id:150, tier:3, tierName:'Brackets', title:'Consecutive even',
    problem:'Three consecutive even numbers add up to 48. What is the smallest?',
    hint:'Let x be the smallest even number', solution:{x:14}, equationCount:1, optimalSteps:3,
    contextAnswer:'The three numbers are 14, 16, and 18.' },
  { id:151, tier:3, tierName:'Brackets', title:'Chocolates per friend',
    problem:'Three friends each start with x chocolates and then receive 2 more each. Together they have 21 chocolates. How many did each friend start with?',
    hint:'Let x be the starting number of chocolates per friend', solution:{x:5}, equationCount:1, optimalSteps:3,
    contextAnswer:'Each friend started with 5 chocolates.' },
  { id:152, tier:3, tierName:'Brackets', title:'Books per shelf',
    problem:'Four shelves each hold the same number of books plus 3 display copies. Total books: 28. How many regular books are on each shelf?',
    hint:'Let x be the number of regular books per shelf', solution:{x:4}, equationCount:1, optimalSteps:3,
    contextAnswer:'Each shelf has 4 regular books.' },
  { id:153, tier:3, tierName:'Brackets', title:'Marbles in bags',
    problem:'Two bags each contain x marbles plus 5 bonus marbles. Total: 26 marbles. Find x.',
    hint:'Let x be the number of regular marbles per bag', solution:{x:8}, equationCount:1, optimalSteps:3,
    contextAnswer:'Each bag has 8 regular marbles.' },
  { id:154, tier:3, tierName:'Brackets', title:'Oranges in boxes',
    problem:'Five boxes each hold x oranges plus 1 extra. There are 30 oranges in total. Find x.',
    hint:'Let x be the base number of oranges per box', solution:{x:5}, equationCount:1, optimalSteps:3,
    contextAnswer:'Each box holds 5 base oranges.' },
  { id:155, tier:3, tierName:'Brackets', title:'Plants in pots',
    problem:'Three pots each have x plants plus 4 seedlings. Altogether there are 33 plants. Find x.',
    hint:'Let x be the number of plants (not seedlings) per pot', solution:{x:7}, equationCount:1, optimalSteps:3,
    contextAnswer:'Each pot has 7 plants.' },
  { id:156, tier:3, tierName:'Brackets', title:'Sum then scale',
    problem:'Twice the sum of a number and 3, plus 5, equals 21. Find the number.',
    hint:'Let x be the number', solution:{x:5}, equationCount:1, optimalSteps:4,
    contextAnswer:'The number is 5.' },
  { id:157, tier:3, tierName:'Brackets', title:'Triple sum',
    problem:'Three times the sum of a number and 2, plus 4, gives 28. Find the number.',
    hint:'Let x be the number', solution:{x:6}, equationCount:1, optimalSteps:4,
    contextAnswer:'The number is 6.' },
  { id:158, tier:3, tierName:'Brackets', title:'Four times sum',
    problem:'Four times the sum of a number and 1, plus 8, equals 32. Find the number.',
    hint:'Let x be the number', solution:{x:5}, equationCount:1, optimalSteps:4,
    contextAnswer:'The number is 5.' },
  { id:159, tier:3, tierName:'Brackets', title:'Double sum plus 6',
    problem:'Twice the sum of x and 5, plus 6, equals 28. Find x.',
    hint:'Let x be the number', solution:{x:6}, equationCount:1, optimalSteps:4,
    contextAnswer:'x = 6.' },
  { id:160, tier:3, tierName:'Brackets', title:'Triple sum plus 3',
    problem:'Three times the sum of a number and 4, plus 3, gives 30. Find the number.',
    hint:'Let x be the number', solution:{x:5}, equationCount:1, optimalSteps:4,
    contextAnswer:'The number is 5.' },

  // ── Tier 4: Fractions & Ratios (161-175) ─────────────────────
  { id:161, tier:4, tierName:'Fractions & Ratios', title:'Half plus third',
    problem:'Half of a number plus a third of the same number equals 5. Find the number.',
    hint:'Let x be the number', solution:{x:6}, equationCount:1, optimalSteps:3,
    contextAnswer:'The number is 6.' },
  { id:162, tier:4, tierName:'Fractions & Ratios', title:'Half plus quarter',
    problem:'Half a number plus a quarter of it equals 6. What is the number?',
    hint:'Let x be the number', solution:{x:8}, equationCount:1, optimalSteps:3,
    contextAnswer:'The number is 8.' },
  { id:163, tier:4, tierName:'Fractions & Ratios', title:'Third plus sixth',
    problem:'A third of a number plus a sixth of it equals 5. Find the number.',
    hint:'Let x be the number', solution:{x:10}, equationCount:1, optimalSteps:3,
    contextAnswer:'The number is 10.' },
  { id:164, tier:4, tierName:'Fractions & Ratios', title:'Half plus fifth',
    problem:'Half a number plus a fifth of it is 7. What is the number?',
    hint:'Let x be the number', solution:{x:10}, equationCount:1, optimalSteps:3,
    contextAnswer:'The number is 10.' },
  { id:165, tier:4, tierName:'Fractions & Ratios', title:'Third plus quarter',
    problem:'A third plus a quarter of a number equals 7. Find the number.',
    hint:'Let x be the number', solution:{x:12}, equationCount:1, optimalSteps:3,
    contextAnswer:'The number is 12.' },
  { id:166, tier:4, tierName:'Fractions & Ratios', title:'Spent a third',
    problem:'Emma spends a third of her money and has £8 left. How much did she start with?',
    hint:'Let x be the starting amount in £', solution:{x:12}, equationCount:1, optimalSteps:3,
    contextAnswer:'Emma started with £12.' },
  { id:167, tier:4, tierName:'Fractions & Ratios', title:'Spent a quarter',
    problem:'Liam spends a quarter of his savings. He has £9 left. What did he start with?',
    hint:'Let x be the starting savings in £', solution:{x:12}, equationCount:1, optimalSteps:3,
    contextAnswer:'Liam started with £12.' },
  { id:168, tier:4, tierName:'Fractions & Ratios', title:'Sweets eaten',
    problem:'A fifth of the sweets are eaten. 12 remain. How many were there to start?',
    hint:'Let x be the starting number of sweets', solution:{x:15}, equationCount:1, optimalSteps:3,
    contextAnswer:'There were 15 sweets to start.' },
  { id:169, tier:4, tierName:'Fractions & Ratios', title:'Cake slices',
    problem:'A third of a cake is eaten. 10 slices remain. How many slices were there in total?',
    hint:'Let x be the total number of slices', solution:{x:15}, equationCount:1, optimalSteps:3,
    contextAnswer:'There were 15 slices in total.' },
  { id:170, tier:4, tierName:'Fractions & Ratios', title:'Two fifths removed',
    problem:'Two fifths of a number is subtracted from it, leaving 12. Find the number.',
    hint:'Let x be the number', solution:{x:20}, equationCount:1, optimalSteps:3,
    contextAnswer:'The number is 20.' },
  { id:171, tier:4, tierName:'Fractions & Ratios', title:'Cats and dogs ratio',
    problem:'The ratio of cats to dogs is 3:2. There are 12 cats. How many dogs are there?',
    hint:'Let x be the number of dogs', solution:{x:8}, equationCount:1, optimalSteps:2,
    contextAnswer:'There are 8 dogs.' },
  { id:172, tier:4, tierName:'Fractions & Ratios', title:'Red and blue balls',
    problem:'For every 4 red balls there are 3 blue ones. There are 16 red balls. How many blue?',
    hint:'Let x be the number of blue balls', solution:{x:12}, equationCount:1, optimalSteps:2,
    contextAnswer:'There are 12 blue balls.' },
  { id:173, tier:4, tierName:'Fractions & Ratios', title:'Recipe ratio',
    problem:'A recipe uses flour and sugar in ratio 5:4. If 20g of flour is used, how much sugar is needed?',
    hint:'Let x be the amount of sugar in grams', solution:{x:16}, equationCount:1, optimalSteps:2,
    contextAnswer:'16g of sugar is needed.' },
  { id:174, tier:4, tierName:'Fractions & Ratios', title:'Girls and boys',
    problem:'The ratio of girls to boys in a class is 2:3. There are 10 girls. How many boys are there?',
    hint:'Let x be the number of boys', solution:{x:15}, equationCount:1, optimalSteps:2,
    contextAnswer:'There are 15 boys.' },
  { id:175, tier:4, tierName:'Fractions & Ratios', title:'Apples and oranges',
    problem:'The ratio of apples to oranges is 3:7. There are 9 apples. How many oranges are there?',
    hint:'Let x be the number of oranges', solution:{x:21}, equationCount:1, optimalSteps:2,
    contextAnswer:'There are 21 oranges.' },

  // ── Tier 5: Challenge (176-185) ──────────────────────────────
  { id:176, tier:5, tierName:'Challenge', title:'Walking and running',
    problem:'Sam walks at 3km/h for x hours, then runs for 2 hours at 5km/h. The total distance is 16km. How long did Sam walk?',
    hint:'Let x be the number of hours Sam walked', solution:{x:2}, equationCount:1, optimalSteps:3,
    contextAnswer:'Sam walked for 2 hours.' },
  { id:177, tier:5, tierName:'Challenge', title:'Cycling journey',
    problem:'A cyclist rides at 4km/h for x hours, then 1 hour at 6km/h. Total distance: 14km. How long was the slow part?',
    hint:'Let x be the number of hours at slow speed', solution:{x:2}, equationCount:1, optimalSteps:3,
    contextAnswer:'The slow part lasted 2 hours.' },
  { id:178, tier:5, tierName:'Challenge', title:'Jog then walk',
    problem:'Tom jogs at 2km/h for x hours, then walks for 3 hours at 4km/h. Total distance: 20km. How long did he jog?',
    hint:'Let x be the number of hours Tom jogged', solution:{x:4}, equationCount:1, optimalSteps:3,
    contextAnswer:'Tom jogged for 4 hours.' },
  { id:179, tier:5, tierName:'Challenge', title:'Boat trip',
    problem:'A boat travels at 5km/h for x hours, then 2 hours at 3km/h. Total distance: 21km. Find x.',
    hint:'Let x be the number of hours at 5km/h', solution:{x:3}, equationCount:1, optimalSteps:3,
    contextAnswer:'The boat travelled at 5km/h for 3 hours.' },
  { id:180, tier:5, tierName:'Challenge', title:'Run then walk',
    problem:'A runner runs at 3km/h for x hours then walks for 4 hours at 2km/h. Total distance: 17km. Find x.',
    hint:'Let x be the number of hours running', solution:{x:3}, equationCount:1, optimalSteps:3,
    contextAnswer:'The runner ran for 3 hours.' },
  { id:181, tier:5, tierName:'Challenge', title:'Age relationship I',
    problem:'Ali is 10 years older than Ben. Ali\'s age is 3 times Ben\'s age. How old is Ben?',
    hint:'Let x be Ben\'s age', solution:{x:5}, equationCount:1, optimalSteps:3,
    contextAnswer:'Ben is 5 years old. Ali is 15.' },
  { id:182, tier:5, tierName:'Challenge', title:'Cat and kitten ages',
    problem:'A cat is 12 years older than a kitten. The cat is 4 times the kitten\'s age. How old is the kitten?',
    hint:'Let x be the kitten\'s age', solution:{x:4}, equationCount:1, optimalSteps:3,
    contextAnswer:'The kitten is 4 years old. The cat is 16.' },
  { id:183, tier:5, tierName:'Challenge', title:'Sister ages',
    problem:'Sara is 15 years older than her sister. Sara is 4 times her sister\'s age. How old is the sister?',
    hint:'Let x be the sister\'s age', solution:{x:5}, equationCount:1, optimalSteps:3,
    contextAnswer:'The sister is 5 years old. Sara is 20.' },
  { id:184, tier:5, tierName:'Challenge', title:'Tom and Jack',
    problem:'Tom is 8 years older than Jack. Tom is 3 times Jack\'s age. How old is Jack?',
    hint:'Let x be Jack\'s age', solution:{x:4}, equationCount:1, optimalSteps:3,
    contextAnswer:'Jack is 4 years old. Tom is 12.' },
  { id:185, tier:5, tierName:'Challenge', title:'Tree and shrub',
    problem:'A tree is 20 years older than a shrub. The tree is 3 times the shrub\'s age. Find the shrub\'s age.',
    hint:'Let x be the age of the shrub', solution:{x:10}, equationCount:1, optimalSteps:3,
    contextAnswer:'The shrub is 10 years old. The tree is 30.' },

  // ── Tier 6: Word Systems I (186-193) ─────────────────────────
  { id:186, tier:6, tierName:'Word Systems I', title:'Sum and difference',
    problem:'Two numbers add up to 20. Their difference is 4. Find both numbers.',
    hint:'Let x be the larger number, y the smaller', solution:{x:12,y:8}, equationCount:2, optimalSteps:4,
    contextAnswer:'The two numbers are 12 and 8.' },
  { id:187, tier:6, tierName:'Word Systems I', title:'One more than other',
    problem:'Two numbers sum to 18. One is 6 more than the other. Find both.',
    hint:'Let x be the larger number, y the smaller', solution:{x:12,y:6}, equationCount:2, optimalSteps:4,
    contextAnswer:'The two numbers are 12 and 6.' },
  { id:188, tier:6, tierName:'Word Systems I', title:'Apple boxes',
    problem:'Together two boxes hold 30 apples. The larger box holds 8 more. How many apples are in each box?',
    hint:'Let x be the number in the large box, y in the small box', solution:{x:19,y:11}, equationCount:2, optimalSteps:4,
    contextAnswer:'The large box has 19 apples, the small box has 11.' },
  { id:189, tier:6, tierName:'Word Systems I', title:'Scores',
    problem:'Sam and Ali together score 24 points. Sam scores 2 more than Ali. Find each score.',
    hint:'Let x be Sam\'s score, y be Ali\'s score', solution:{x:13,y:11}, equationCount:2, optimalSteps:4,
    contextAnswer:'Sam scored 13 points. Ali scored 11.' },
  { id:190, tier:6, tierName:'Word Systems I', title:'Pens and rulers',
    problem:'2 pens and 3 rulers cost £13. A pen and a ruler together cost £5. How much is each?',
    hint:'Let x be the price of a pen, y the price of a ruler (in £)', solution:{x:2,y:3}, equationCount:2, optimalSteps:5,
    contextAnswer:'A pen costs £2. A ruler costs £3.' },
  { id:191, tier:6, tierName:'Word Systems I', title:'Coffee and tea',
    problem:'3 coffees and 2 teas cost £17. A coffee and a tea together cost £7. Find each price.',
    hint:'Let x be the price of a coffee, y the price of a tea (in £)', solution:{x:3,y:4}, equationCount:2, optimalSteps:5,
    contextAnswer:'A coffee costs £3. A tea costs £4.' },
  { id:192, tier:6, tierName:'Word Systems I', title:'Sandwiches and cakes',
    problem:'4 sandwiches and 3 cakes cost £26. A sandwich and a cake together cost £7. Find each price.',
    hint:'Let x be the price of a sandwich, y the price of a cake (in £)', solution:{x:5,y:2}, equationCount:2, optimalSteps:5,
    contextAnswer:'A sandwich costs £5. A cake costs £2.' },
  { id:193, tier:6, tierName:'Word Systems I', title:'Hot dogs and drinks',
    problem:'3 hot dogs and 4 drinks cost £26. 2 hot dogs and 1 drink cost £14. Find each price.',
    hint:'Let x be the price of a hot dog, y the price of a drink (in £)', solution:{x:6,y:2}, equationCount:2, optimalSteps:5,
    contextAnswer:'A hot dog costs £6. A drink costs £2.' },

  // ── Tier 7: Word Systems II (194-200) ────────────────────────
  { id:194, tier:7, tierName:'Word Systems II', title:'Two numbers',
    problem:'Twice a number added to three times another equals 23. The first number is 4 more than the second. Find both.',
    hint:'Let x be the first number, y the second', solution:{x:7,y:3}, equationCount:2, optimalSteps:6,
    contextAnswer:'The two numbers are 7 and 3.' },
  { id:195, tier:7, tierName:'Word Systems II', title:'Sum and expression',
    problem:'Two numbers have a sum of 13. Three times the larger minus twice the smaller is 14. Find both.',
    hint:'Let x be the larger number, y the smaller', solution:{x:8,y:5}, equationCount:2, optimalSteps:6,
    contextAnswer:'The two numbers are 8 and 5.' },
  { id:196, tier:7, tierName:'Word Systems II', title:'Two expressions',
    problem:'Five times a number minus three times another is 18. Twice the first plus the second is 16. Find both.',
    hint:'Let x be the first number, y the second', solution:{x:6,y:4}, equationCount:2, optimalSteps:6,
    contextAnswer:'The two numbers are 6 and 4.' },
  { id:197, tier:7, tierName:'Word Systems II', title:'Sum and difference II',
    problem:'Two numbers sum to 13. Three times the first minus twice the second is 19. Find both.',
    hint:'Let x be the first number, y the second', solution:{x:9,y:4}, equationCount:2, optimalSteps:6,
    contextAnswer:'The two numbers are 9 and 4.' },
  { id:198, tier:7, tierName:'Word Systems II', title:'Adult and child tickets',
    problem:'2 adult tickets and 3 child tickets cost £29. An adult ticket costs £2 more than a child ticket. Find each price.',
    hint:'Let x be the adult ticket price, y the child ticket price (in £)', solution:{x:7,y:5}, equationCount:2, optimalSteps:6,
    contextAnswer:'An adult ticket costs £7. A child ticket costs £5.' },
  { id:199, tier:7, tierName:'Word Systems II', title:'Chocolate and gum',
    problem:'4 chocolate bars and 1 pack of gum cost £23. 2 chocolate bars and 3 packs of gum cost £19. Find each price.',
    hint:'Let x be the price of a chocolate bar, y the price of a pack of gum (in £)', solution:{x:5,y:3}, equationCount:2, optimalSteps:6,
    contextAnswer:'A chocolate bar costs £5. A pack of gum costs £3.' },
  { id:200, tier:7, tierName:'Word Systems II', title:'Rectangle dimensions',
    problem:'A rectangle has a perimeter of 20cm. The width is 2cm less than the length. Find both dimensions.',
    hint:'Let x be the length, y the width (in cm)', solution:{x:6,y:4}, equationCount:2, optimalSteps:6,
    contextAnswer:'The length is 6cm. The width is 4cm.' },
];
