export const WORD_PROBLEMS = [
  // ── Tier 1: Word Starters (101-120) ──────────────────────────
  { id:101, tier:1, tierName:'Word Starters', title:'Number plus its double',
    problem:'A number added to its own double makes 18. Find the number.',
    hint:'Let x be the number. "Its double" is 2x, so write x + 2x = 18', solution:{x:6}, equationCount:1, optimalSteps:2,
    contextAnswer:'The number is 6.' },
  { id:102, tier:1, tierName:'Word Starters', title:'Adding gives double',
    problem:'I add 7 to a number and the result is exactly twice the number. What is the number?',
    hint:'Let x be the number. "Twice the number" is 2x, so x + 7 = 2x', solution:{x:7}, equationCount:1, optimalSteps:2,
    contextAnswer:'The number is 7.' },
  { id:103, tier:1, tierName:'Word Starters', title:'More than its half',
    problem:'A number is 5 more than its own half. Find the number.',
    hint:'Let x be the number. "Its half" is x/2, so x/2 + 5 = x', solution:{x:10}, equationCount:1, optimalSteps:2,
    contextAnswer:'The number is 10.' },
  { id:104, tier:1, tierName:'Word Starters', title:'Triple minus 5',
    problem:'I triple a number and subtract 5. The result equals double the number. Find the number.',
    hint:'Let x be the number. Triple is 3x, double is 2x, so 3x - 5 = 2x', solution:{x:5}, equationCount:1, optimalSteps:2,
    contextAnswer:'The number is 5.' },
  { id:105, tier:1, tierName:'Word Starters', title:'Plus 16 gives triple',
    problem:'A number plus 16 equals three times that number. Find the number.',
    hint:'Let x be the number. x + 16 = 3x', solution:{x:8}, equationCount:1, optimalSteps:2,
    contextAnswer:'The number is 8.' },
  { id:106, tier:1, tierName:'Word Starters', title:'Subtract from 30',
    problem:'I subtract a number from 30 and get twice the number. What is the number?',
    hint:'Let x be the number. 30 - x = 2x', solution:{x:10}, equationCount:1, optimalSteps:2,
    contextAnswer:'The number is 10.' },
  { id:107, tier:1, tierName:'Word Starters', title:'Four times minus 24',
    problem:'Four times a number, take away 24, equals the number itself. Find the number.',
    hint:'Let x be the number. 4x - 24 = x', solution:{x:8}, equationCount:1, optimalSteps:2,
    contextAnswer:'The number is 8.' },
  { id:108, tier:1, tierName:'Word Starters', title:'Number plus its triple',
    problem:'A number added to its own triple equals 28. Find the number.',
    hint:'Let x be the number. "Its triple" is 3x, so x + 3x = 28', solution:{x:7}, equationCount:1, optimalSteps:2,
    contextAnswer:'The number is 7.' },
  { id:109, tier:1, tierName:'Word Starters', title:'Double vs triple',
    problem:'I double a number and add 3. This gives the same result as trebling the number minus 5. Find the number.',
    hint:'Let x be the number. 2x + 3 = 3x - 5', solution:{x:8}, equationCount:1, optimalSteps:3,
    contextAnswer:'The number is 8.' },
  { id:110, tier:1, tierName:'Word Starters', title:'Five times vs twice',
    problem:'Five times a number, take away 6, equals twice the number plus 9. Find the number.',
    hint:'Let x be the number. 5x - 6 = 2x + 9', solution:{x:5}, equationCount:1, optimalSteps:3,
    contextAnswer:'The number is 5.' },
  { id:111, tier:1, tierName:'Word Starters', title:'Two related numbers',
    problem:'A number and 4 more than that number add up to 26. Find the smaller number.',
    hint:'Let x be the smaller number. The larger is x + 4, so x + (x + 4) = 26', solution:{x:11}, equationCount:1, optimalSteps:2,
    contextAnswer:'The smaller number is 11.' },
  { id:112, tier:1, tierName:'Word Starters', title:'Three in a row',
    problem:'Three consecutive whole numbers add up to 39. Find the smallest.',
    hint:'Let x be the smallest. The three numbers are x, x+1, x+2, so x + (x+1) + (x+2) = 39', solution:{x:12}, equationCount:1, optimalSteps:2,
    contextAnswer:'The smallest number is 12. The three numbers are 12, 13, and 14.' },
  { id:113, tier:1, tierName:'Word Starters', title:'Sum and gap',
    problem:'Two numbers add up to 44. The larger is 8 more than the smaller. Find the smaller number.',
    hint:'Let x be the smaller. The larger is x + 8, so x + (x + 8) = 44', solution:{x:18}, equationCount:1, optimalSteps:2,
    contextAnswer:'The smaller number is 18. The two numbers are 18 and 26.' },
  { id:114, tier:1, tierName:'Word Starters', title:'Subtract to get four times',
    problem:'I subtract a number from 55 and the result is 4 times the number. Find the number.',
    hint:'Let x be the number. 55 - x = 4x', solution:{x:11}, equationCount:1, optimalSteps:2,
    contextAnswer:'The number is 11.' },
  { id:115, tier:1, tierName:'Word Starters', title:'Plus 9 vs double minus 5',
    problem:'A number plus 9 equals double the number take away 5. Find the number.',
    hint:'Let x be the number. x + 9 = 2x - 5', solution:{x:14}, equationCount:1, optimalSteps:2,
    contextAnswer:'The number is 14.' },
  { id:116, tier:1, tierName:'Word Starters', title:'Half of 30',
    problem:'I subtract a number from 30. The result equals the number itself. Find the number.',
    hint:'Let x be the number. 30 - x = x', solution:{x:15}, equationCount:1, optimalSteps:2,
    contextAnswer:'The number is 15.' },
  { id:117, tier:1, tierName:'Word Starters', title:'Four times vs 60 minus',
    problem:'Four times a number equals 60 minus the number. Find the number.',
    hint:'Let x be the number. 4x = 60 - x', solution:{x:12}, equationCount:1, optimalSteps:2,
    contextAnswer:'The number is 12.' },
  { id:118, tier:1, tierName:'Word Starters', title:'More than two thirds',
    problem:'A number is 3 more than two thirds of itself. Find the number.',
    hint:'Let x be the number. Two thirds of x is 2x/3, so x = 2x/3 + 3', solution:{x:9}, equationCount:1, optimalSteps:3,
    contextAnswer:'The number is 9.' },
  { id:119, tier:1, tierName:'Word Starters', title:'Six times vs plus 30',
    problem:'Six times a number equals the number plus 30. Find the number.',
    hint:'Let x be the number. 6x = x + 30', solution:{x:6}, equationCount:1, optimalSteps:2,
    contextAnswer:'The number is 6.' },
  { id:120, tier:1, tierName:'Word Starters', title:'Double minus 7',
    problem:'I double a number and take away 7. The result equals the number plus 3. Find the number.',
    hint:'Let x be the number. 2x - 7 = x + 3', solution:{x:10}, equationCount:1, optimalSteps:2,
    contextAnswer:'The number is 10.' },

  // ── Tier 2: Two Steps (121-140) ──────────────────────────────
  { id:121, tier:2, tierName:'Two Steps', title:'Plumber call-out',
    problem:'A plumber charges a £35 call-out fee, then £22 per hour. The total bill is £101. How many hours did the plumber work?',
    hint:'Let x be the hours. The bill is: call-out + hours × rate = total, so 22x + 35 = 101',
    solution:{x:3}, equationCount:1, optimalSteps:2,
    contextAnswer:'The plumber worked 3 hours. Check: 35 + 22×3 = 35 + 66 = 101 ✓' },
  { id:122, tier:2, tierName:'Two Steps', title:'Gym membership',
    problem:'A gym charges a £40 joining fee, then £15 per month. After how many months will the total cost be £160?',
    hint:'Let x be the months. Joining fee + months × monthly rate = total, so 15x + 40 = 160',
    solution:{x:8}, equationCount:1, optimalSteps:2,
    contextAnswer:'After 8 months. Check: 40 + 15×8 = 40 + 120 = 160 ✓' },
  { id:123, tier:2, tierName:'Two Steps', title:'Phone plan',
    problem:'A phone plan has a £20 setup fee and costs £12 per month. After how many months will the total be £92?',
    hint:'Let x be the months. Setup fee + months × monthly cost = total, so 12x + 20 = 92',
    solution:{x:6}, equationCount:1, optimalSteps:2,
    contextAnswer:'After 6 months. Check: 20 + 12×6 = 20 + 72 = 92 ✓' },
  { id:124, tier:2, tierName:'Two Steps', title:'Taxi fare',
    problem:'A taxi charges £2 to start the meter, then £3 per mile. A journey costs £17. How many miles was the journey?',
    hint:'Let x be the miles. Flag-fall + miles × rate = total, so 3x + 2 = 17',
    solution:{x:5}, equationCount:1, optimalSteps:2,
    contextAnswer:'The journey was 5 miles. Check: 2 + 3×5 = 2 + 15 = 17 ✓' },
  { id:125, tier:2, tierName:'Two Steps', title:'Saving up',
    problem:'Maria already has £24 saved. She saves £8 per week. After how many weeks will she have £80?',
    hint:'Let x be the weeks. Current savings + weeks × weekly amount = target, so 8x + 24 = 80',
    solution:{x:7}, equationCount:1, optimalSteps:2,
    contextAnswer:'After 7 weeks. Check: 24 + 8×7 = 24 + 56 = 80 ✓' },
  { id:126, tier:2, tierName:'Two Steps', title:'Baker profit',
    problem:'A baker spends £8 per day on ingredients. Each loaf sells for £2. How many loaves must be sold to make a daily profit of £22?',
    hint:'Let x be the loaves sold. Profit = revenue − costs, so 2x − 8 = 22',
    solution:{x:15}, equationCount:1, optimalSteps:2,
    contextAnswer:'15 loaves. Check: 2×15 − 8 = 30 − 8 = 22 ✓' },
  { id:127, tier:2, tierName:'Two Steps', title:'Car hire',
    problem:'A car hire company charges a £50 booking fee plus £25 per day. A customer pays £250 total. How many days did they hire the car?',
    hint:'Let x be the days. Booking fee + days × daily rate = total, so 25x + 50 = 250',
    solution:{x:8}, equationCount:1, optimalSteps:2,
    contextAnswer:'8 days. Check: 50 + 25×8 = 50 + 200 = 250 ✓' },
  { id:128, tier:2, tierName:'Two Steps', title:'Magazine subscription',
    problem:'A magazine subscription costs £12 per month. You also paid a £36 joining fee upfront. After how many months will your total spend be £132?',
    hint:'Let x be the months. Joining fee + months × monthly cost = total, so 12x + 36 = 132',
    solution:{x:8}, equationCount:1, optimalSteps:2,
    contextAnswer:'After 8 months. Check: 36 + 12×8 = 36 + 96 = 132 ✓' },
  { id:129, tier:2, tierName:'Two Steps', title:'Football card rivalry',
    problem:'Ali has 4 times as many football cards as Ben. Ali has 21 more cards than Ben. How many cards does Ben have?',
    hint:'Let x be Ben\'s cards. Ali\'s count can be written two ways: 4x and x + 21. Set them equal: 4x = x + 21',
    solution:{x:7}, equationCount:1, optimalSteps:2,
    contextAnswer:'Ben has 7 cards, Ali has 28. Check: 28 = 4×7 ✓ and 28 − 7 = 21 ✓' },
  { id:130, tier:2, tierName:'Two Steps', title:'Age gap',
    problem:'Tom is 5 times as old as Sam. Tom is 16 years older than Sam. How old is Sam?',
    hint:'Let x be Sam\'s age. Tom\'s age is both 5x and x + 16. So 5x = x + 16',
    solution:{x:4}, equationCount:1, optimalSteps:2,
    contextAnswer:'Sam is 4, Tom is 20. Check: 20 = 5×4 ✓ and 20 − 4 = 16 ✓' },
  { id:131, tier:2, tierName:'Two Steps', title:'Train speeds',
    problem:'An express train travels at 3 times the speed of a local train. The express is 80 mph faster than the local. What is the speed of the local train?',
    hint:'Let x be the local speed in mph. Express speed is both 3x and x + 80. So 3x = x + 80',
    solution:{x:40}, equationCount:1, optimalSteps:2,
    contextAnswer:'Local: 40 mph, Express: 120 mph. Check: 120 = 3×40 ✓ and 120 − 40 = 80 ✓' },
  { id:132, tier:2, tierName:'Two Steps', title:'Fridge cooling',
    problem:'A fridge starts at 18°C and cools by 3°C every hour. After how many hours will the temperature reach −3°C?',
    hint:'Let x be the hours. Starting temp − cooling per hour × hours = final temp, so 18 − 3x = −3',
    solution:{x:7}, equationCount:1, optimalSteps:2,
    contextAnswer:'After 7 hours. Check: 18 − 3×7 = 18 − 21 = −3 ✓' },
  { id:133, tier:2, tierName:'Two Steps', title:'Quiz scoring',
    problem:'A quiz starts you on 40 points. Each wrong answer loses 2 points. A player finishes with 26 points. How many questions did they get wrong?',
    hint:'Let x be the wrong answers. Starting score − losses = final score, so 40 − 2x = 26',
    solution:{x:7}, equationCount:1, optimalSteps:2,
    contextAnswer:'7 wrong answers. Check: 40 − 2×7 = 40 − 14 = 26 ✓' },
  { id:134, tier:2, tierName:'Two Steps', title:'Electrician',
    problem:'An electrician charges a £30 call-out fee, then £45 per hour. The total invoice is £210. How many hours did the electrician work?',
    hint:'Let x be the hours. Call-out fee + hours × rate = total, so 45x + 30 = 210',
    solution:{x:4}, equationCount:1, optimalSteps:2,
    contextAnswer:'4 hours. Check: 30 + 45×4 = 30 + 180 = 210 ✓' },
  { id:135, tier:2, tierName:'Two Steps', title:'Sticker album',
    problem:'An album already has 16 stickers. Each pack adds 8 stickers. How many packs are needed to reach 80 stickers in total?',
    hint:'Let x be the packs. Current stickers + packs × per pack = target, so 8x + 16 = 80',
    solution:{x:8}, equationCount:1, optimalSteps:2,
    contextAnswer:'8 packs. Check: 16 + 8×8 = 16 + 64 = 80 ✓' },
  { id:136, tier:2, tierName:'Two Steps', title:'Online order',
    problem:'An online shop charges £5 for delivery plus £3 per item. An order costs £29 in total. How many items were ordered?',
    hint:'Let x be the items. Delivery + items × price per item = total, so 3x + 5 = 29',
    solution:{x:8}, equationCount:1, optimalSteps:2,
    contextAnswer:'8 items. Check: 5 + 3×8 = 5 + 24 = 29 ✓' },
  { id:137, tier:2, tierName:'Two Steps', title:'Cinema family',
    problem:'Cinema tickets cost £5 each for children and £9 for one adult. The family total is £29. How many children are there?',
    hint:'Let x be the children. Adult ticket + children × child ticket price = total, so 9 + 5x = 29',
    solution:{x:4}, equationCount:1, optimalSteps:2,
    contextAnswer:'4 children. Check: 9 + 5×4 = 9 + 20 = 29 ✓' },
  { id:138, tier:2, tierName:'Two Steps', title:'Bus journey',
    problem:'A bus waits 60 minutes at the terminus before departure, then takes 2 minutes per stop. The whole trip takes 180 minutes. How many stops does it make?',
    hint:'Let x be the stops. Waiting time + stops × minutes per stop = total time, so 2x + 60 = 180',
    solution:{x:60}, equationCount:1, optimalSteps:2,
    contextAnswer:'60 stops. Check: 60 + 2×60 = 60 + 120 = 180 ✓' },
  { id:139, tier:2, tierName:'Two Steps', title:'Farm animals',
    problem:'A farmer has some cows. He has 15 more sheep than cows. In total there are 31 animals. How many cows are there?',
    hint:'Let x be the cows. Sheep = x + 15. Total: x + (x + 15) = 31, which gives 2x + 15 = 31',
    solution:{x:8}, equationCount:1, optimalSteps:2,
    contextAnswer:'8 cows and 23 sheep. Check: 8 + 23 = 31 ✓ and 23 − 8 = 15 ✓' },
  { id:140, tier:2, tierName:'Two Steps', title:'Hotel stay',
    problem:'A hotel charges £80 per night plus a £25 booking fee. A guest pays £345 in total. For how many nights did they stay?',
    hint:'Let x be the nights. Booking fee + nights × nightly rate = total, so 80x + 25 = 345',
    solution:{x:4}, equationCount:1, optimalSteps:2,
    contextAnswer:'4 nights. Check: 25 + 80×4 = 25 + 320 = 345 ✓' },

  // ── Tier 3: Brackets (141-160) ───────────────────────────────
  { id:141, tier:3, tierName:'Brackets', title:'Party bags',
    problem:'5 party bags are prepared. Each bag has x sweets and 3 lollipops. There are 35 items in total. How many sweets are in each bag?',
    hint:'Let x be the sweets per bag. Total items: 5 × (sweets + lollipops) = 35, so 5(x + 3) = 35',
    solution:{x:4}, equationCount:1, optimalSteps:3,
    contextAnswer:'4 sweets per bag. Check: 5 × (4 + 3) = 5 × 7 = 35 ✓' },
  { id:142, tier:3, tierName:'Brackets', title:'School buses',
    problem:'4 buses each carry x pupils and 2 teachers. There are 28 people on the buses altogether. How many pupils are on each bus?',
    hint:'Let x be the pupils per bus. Total people: 4 × (pupils + teachers) = 28, so 4(x + 2) = 28',
    solution:{x:5}, equationCount:1, optimalSteps:3,
    contextAnswer:'5 pupils per bus. Check: 4 × (5 + 2) = 4 × 7 = 28 ✓' },
  { id:143, tier:3, tierName:'Brackets', title:'Flower rows',
    problem:'A garden has 6 identical rows of flowers. Each row has x red flowers and 4 white flowers. There are 48 flowers in total. How many red flowers are in each row?',
    hint:'Let x be the red flowers per row. 6 × (red + white) = 48, so 6(x + 4) = 48',
    solution:{x:4}, equationCount:1, optimalSteps:3,
    contextAnswer:'4 red flowers per row. Check: 6 × (4 + 4) = 6 × 8 = 48 ✓' },
  { id:144, tier:3, tierName:'Brackets', title:'Crates of bottles',
    problem:'3 identical crates each hold x bottles plus 5 foam spacers. The crates together hold 36 items. How many bottles are in each crate?',
    hint:'Let x be the bottles per crate. 3 × (bottles + spacers) = 36, so 3(x + 5) = 36',
    solution:{x:7}, equationCount:1, optimalSteps:3,
    contextAnswer:'7 bottles per crate. Check: 3 × (7 + 5) = 3 × 12 = 36 ✓' },
  { id:145, tier:3, tierName:'Brackets', title:'Cinema rows',
    problem:'4 rows in a cinema each have x adults and 3 children. There are 36 people in those rows. How many adults are in each row?',
    hint:'Let x be the adults per row. 4 × (adults + children) = 36, so 4(x + 3) = 36',
    solution:{x:6}, equationCount:1, optimalSteps:3,
    contextAnswer:'6 adults per row. Check: 4 × (6 + 3) = 4 × 9 = 36 ✓' },
  { id:146, tier:3, tierName:'Brackets', title:'Coin bags',
    problem:'5 bags each contain x gold coins and 2 silver coins. There are 40 coins in total. How many gold coins are in each bag?',
    hint:'Let x be the gold coins per bag. 5 × (gold + silver) = 40, so 5(x + 2) = 40',
    solution:{x:6}, equationCount:1, optimalSteps:3,
    contextAnswer:'6 gold coins per bag. Check: 5 × (6 + 2) = 5 × 8 = 40 ✓' },
  { id:147, tier:3, tierName:'Brackets', title:'Rectangle length',
    problem:'A rectangle has a length 5m more than its width. The perimeter is 34m. Find the width.',
    hint:'Let x be the width. Length = x + 5. Perimeter: 2 × (width + length) = 34, so 2(x + x + 5) = 34',
    solution:{x:6}, equationCount:1, optimalSteps:3,
    contextAnswer:'Width = 6m, Length = 11m. Check: 2(6 + 11) = 2 × 17 = 34 ✓' },
  { id:148, tier:3, tierName:'Brackets', title:'Rectangular field',
    problem:'A rectangular field has a length twice its width. The perimeter is 36m. Find the width.',
    hint:'Let x be the width. Length = 2x. Perimeter: 2(width + length) = 36, so 2(x + 2x) = 36',
    solution:{x:6}, equationCount:1, optimalSteps:3,
    contextAnswer:'Width = 6m, Length = 12m. Check: 2(6 + 12) = 2 × 18 = 36 ✓' },
  { id:149, tier:3, tierName:'Brackets', title:'Consecutive page numbers',
    problem:'Three consecutive page numbers add up to 57. What is the first page number?',
    hint:'Let x be the first page. The three pages are x, x+1, x+2. Their sum: x + (x+1) + (x+2) = 57',
    solution:{x:18}, equationCount:1, optimalSteps:3,
    contextAnswer:'Pages 18, 19, 20. Check: 18 + 19 + 20 = 57 ✓' },
  { id:150, tier:3, tierName:'Brackets', title:'Consecutive even seats',
    problem:'Three consecutive even seat numbers sum to 54. What is the smallest seat number?',
    hint:'Let x be the smallest even number. The seats are x, x+2, x+4. So x + (x+2) + (x+4) = 54',
    solution:{x:16}, equationCount:1, optimalSteps:3,
    contextAnswer:'Seats 16, 18, 20. Check: 16 + 18 + 20 = 54 ✓' },
  { id:151, tier:3, tierName:'Brackets', title:'Siblings\'s ages',
    problem:'Three siblings born one year apart have ages that sum to 27. How old is the youngest?',
    hint:'Let x be the youngest\'s age. Ages are x, x+1, x+2. So x + (x+1) + (x+2) = 27',
    solution:{x:8}, equationCount:1, optimalSteps:3,
    contextAnswer:'Ages 8, 9, 10. Check: 8 + 9 + 10 = 27 ✓' },
  { id:152, tier:3, tierName:'Brackets', title:'Consecutive odd numbers',
    problem:'Four consecutive odd numbers sum to 64. What is the smallest?',
    hint:'Let x be the smallest odd number. The four numbers are x, x+2, x+4, x+6. So x + (x+2) + (x+4) + (x+6) = 64',
    solution:{x:13}, equationCount:1, optimalSteps:3,
    contextAnswer:'Numbers: 13, 15, 17, 19. Check: 13+15+17+19 = 64 ✓' },
  { id:153, tier:3, tierName:'Brackets', title:'Room dimensions',
    problem:'A room\'s length is 3m more than its width. The perimeter is 26m. Find the width.',
    hint:'Let x be the width. Length = x + 3. Perimeter: 2(x + x + 3) = 26',
    solution:{x:5}, equationCount:1, optimalSteps:3,
    contextAnswer:'Width = 5m, Length = 8m. Check: 2(5 + 8) = 2 × 13 = 26 ✓' },
  { id:154, tier:3, tierName:'Brackets', title:'Swimming pool',
    problem:'A swimming pool is 4 times as long as it is wide. The perimeter is 50m. Find the width.',
    hint:'Let x be the width. Length = 4x. Perimeter: 2(x + 4x) = 50',
    solution:{x:5}, equationCount:1, optimalSteps:3,
    contextAnswer:'Width = 5m, Length = 20m. Check: 2(5 + 20) = 2 × 25 = 50 ✓' },
  { id:155, tier:3, tierName:'Brackets', title:'Library shelves',
    problem:'5 shelves each hold x books plus 4 reference copies that never move. The total book count is 65. How many regular books are on each shelf?',
    hint:'Let x be the regular books per shelf. 5 × (regular + reference) = 65, so 5(x + 4) = 65',
    solution:{x:9}, equationCount:1, optimalSteps:3,
    contextAnswer:'9 regular books per shelf. Check: 5 × (9 + 4) = 5 × 13 = 65 ✓' },
  { id:156, tier:3, tierName:'Brackets', title:'Coach passengers',
    problem:'3 coaches each carry x passengers and 1 driver. In total there are 48 people. How many passengers are on each coach?',
    hint:'Let x be passengers per coach. 3 × (passengers + driver) = 48, so 3(x + 1) = 48',
    solution:{x:15}, equationCount:1, optimalSteps:3,
    contextAnswer:'15 passengers per coach. Check: 3 × (15 + 1) = 3 × 16 = 48 ✓' },
  { id:157, tier:3, tierName:'Brackets', title:'Cut rope pieces',
    problem:'A rope is cut into 4 equal pieces. 2m is then trimmed off each piece. The total length remaining is 16m. How long was each piece before trimming?',
    hint:'Let x be the length of each piece before trimming. 4 × (piece − trim) = 16, so 4(x − 2) = 16',
    solution:{x:6}, equationCount:1, optimalSteps:3,
    contextAnswer:'Each piece was 6m. Check: 4 × (6 − 2) = 4 × 4 = 16 ✓' },
  { id:158, tier:3, tierName:'Brackets', title:'Pig pens',
    problem:'A farmer has 6 pens, each with x pigs. He buys 3 more pigs for each pen. He now has 54 pigs in total. How many were in each pen originally?',
    hint:'Let x be the original pigs per pen. 6 × (original + new) = 54, so 6(x + 3) = 54',
    solution:{x:6}, equationCount:1, optimalSteps:3,
    contextAnswer:'6 pigs per pen originally. Check: 6 × (6 + 3) = 6 × 9 = 54 ✓' },
  { id:159, tier:3, tierName:'Brackets', title:'Quiz round points',
    problem:'In a quiz, 4 teams each start with x points and then score 5 more in round 2. The total points across all teams is 48. How many did each team start with?',
    hint:'Let x be the starting points. 4 × (starting + round 2) = 48, so 4(x + 5) = 48',
    solution:{x:7}, equationCount:1, optimalSteps:3,
    contextAnswer:'7 starting points per team. Check: 4 × (7 + 5) = 4 × 12 = 48 ✓' },
  { id:160, tier:3, tierName:'Brackets', title:'Number increased then tripled',
    problem:'A number is increased by 4, and the result is tripled. The final answer is 27. Find the original number.',
    hint:'Let x be the number. "Increased by 4 then tripled" means 3 × (x + 4) = 27',
    solution:{x:5}, equationCount:1, optimalSteps:3,
    contextAnswer:'The number is 5. Check: 3 × (5 + 4) = 3 × 9 = 27 ✓' },

  // ── Tier 4: Fractions & Ratios (161-175) ─────────────────────
  { id:161, tier:4, tierName:'Fractions & Ratios', title:'Spending fractions',
    problem:'You spend 1/3 of your money on food and 1/4 on transport. You have £15 left. How much did you start with?',
    hint:'Let x be your starting amount. After spending: x − x/3 − x/4 = 15. Find a common denominator.',
    solution:{x:36}, equationCount:1, optimalSteps:3,
    contextAnswer:'£36. Check: 36 − 12 − 9 = 15 ✓' },
  { id:162, tier:4, tierName:'Fractions & Ratios', title:'Train capacity',
    problem:'A train is 3/4 full. At the next station 30 more passengers board and the train is now completely full. How many passengers does the train hold?',
    hint:'Let x be the train\'s capacity. The empty fraction is 1/4, so x/4 = 30',
    solution:{x:120}, equationCount:1, optimalSteps:2,
    contextAnswer:'120 passengers. Check: 3/4 × 120 = 90, and 90 + 30 = 120 ✓' },
  { id:163, tier:4, tierName:'Fractions & Ratios', title:'Maya\'s savings',
    problem:'After spending 2/5 of her savings, Maya has £18 left. How much did she start with?',
    hint:'Let x be her starting amount. She keeps 3/5, so 3x/5 = 18',
    solution:{x:30}, equationCount:1, optimalSteps:2,
    contextAnswer:'£30. Check: 2/5 × 30 = 12 spent, 30 − 12 = 18 ✓' },
  { id:164, tier:4, tierName:'Fractions & Ratios', title:'Class vote',
    problem:'5/8 of a class votes yes on a school trip. The remaining 15 students vote no. How many students are in the class?',
    hint:'Let x be the class size. The "no" fraction is 3/8, so 3x/8 = 15',
    solution:{x:40}, equationCount:1, optimalSteps:2,
    contextAnswer:'40 students. Check: 5/8 × 40 = 25 yes, 3/8 × 40 = 15 no ✓' },
  { id:165, tier:4, tierName:'Fractions & Ratios', title:'Sweet jar',
    problem:'A jar is 2/3 full of sweets. After eating 8, the jar is exactly half full. How many sweets does a full jar hold?',
    hint:'Let x be the full jar capacity. Before: 2x/3. After eating 8: 2x/3 − 8 = x/2',
    solution:{x:48}, equationCount:1, optimalSteps:3,
    contextAnswer:'48 sweets. Check: 2/3 × 48 = 32, 32 − 8 = 24 = 48/2 ✓' },
  { id:166, tier:4, tierName:'Fractions & Ratios', title:'Divide and add',
    problem:'Dividing a number by 3, then adding 7, gives 15. Find the number.',
    hint:'Let x be the number. x/3 + 7 = 15',
    solution:{x:24}, equationCount:1, optimalSteps:2,
    contextAnswer:'24. Check: 24/3 + 7 = 8 + 7 = 15 ✓' },
  { id:167, tier:4, tierName:'Fractions & Ratios', title:'Half plus double',
    problem:'Half of a number plus twice the same number equals 25. Find the number.',
    hint:'Let x be the number. x/2 + 2x = 25. Combine over a common denominator.',
    solution:{x:10}, equationCount:1, optimalSteps:3,
    contextAnswer:'10. Check: 10/2 + 2×10 = 5 + 20 = 25 ✓' },
  { id:168, tier:4, tierName:'Fractions & Ratios', title:'Baking ratio',
    problem:'A recipe uses flour and sugar in ratio 3:2. You use 150g of flour. How much sugar do you need?',
    hint:'Let x be the sugar in grams. The ratio gives 150/x = 3/2, so 3x = 300',
    solution:{x:100}, equationCount:1, optimalSteps:2,
    contextAnswer:'100g of sugar. Check: 150:100 = 3:2 ✓' },
  { id:169, tier:4, tierName:'Fractions & Ratios', title:'Concrete mix',
    problem:'Concrete is made from sand and cement in ratio 5:1. A total of 60kg is mixed. How much cement is used?',
    hint:'Let x be the cement in kg. Sand = 5x. Total: x + 5x = 60',
    solution:{x:10}, equationCount:1, optimalSteps:2,
    contextAnswer:'10kg of cement and 50kg of sand. Check: 10 + 50 = 60 ✓ and 50:10 = 5:1 ✓' },
  { id:170, tier:4, tierName:'Fractions & Ratios', title:'Mixing paint',
    problem:'Blue and yellow paint are mixed in ratio 3:5. The total amount of paint is 24 litres. How many litres of blue paint are used?',
    hint:'Let x be the blue paint in litres. Yellow = 24 − x. The ratio gives x/(24−x) = 3/5',
    solution:{x:9}, equationCount:1, optimalSteps:3,
    contextAnswer:'9 litres of blue. Check: 9:15 = 3:5 ✓ and 9 + 15 = 24 ✓' },
  { id:171, tier:4, tierName:'Fractions & Ratios', title:'Two numbers in ratio',
    problem:'Two numbers are in ratio 2:3 and sum to 35. Find the smaller number.',
    hint:'Let x be the smaller number. The larger is 3x/2. So x + 3x/2 = 35',
    solution:{x:14}, equationCount:1, optimalSteps:3,
    contextAnswer:'14 and 21. Check: 14 + 21 = 35 ✓ and 14:21 = 2:3 ✓' },
  { id:172, tier:4, tierName:'Fractions & Ratios', title:'Ages in ratio',
    problem:'The ages of A and B are in ratio 3:4. A is 21 years old. How old is B?',
    hint:'Let x be B\'s age. The ratio gives 21/x = 3/4, so 3x = 84',
    solution:{x:28}, equationCount:1, optimalSteps:2,
    contextAnswer:'B is 28. Check: 21:28 = 3:4 ✓' },
  { id:173, tier:4, tierName:'Fractions & Ratios', title:'Gold and silver alloy',
    problem:'An alloy contains gold and silver in ratio 2:7. There is 14g of gold. How much silver is there?',
    hint:'Let x be the silver in grams. The ratio gives 14/x = 2/7, so 2x = 98',
    solution:{x:49}, equationCount:1, optimalSteps:2,
    contextAnswer:'49g of silver. Check: 14:49 = 2:7 ✓' },
  { id:174, tier:4, tierName:'Fractions & Ratios', title:'Class total',
    problem:'In a class, the ratio of girls to boys is 4:5. There are 20 girls. How many students are there in total?',
    hint:'Let x be the total students. Girls are 4/9 of the total, so 4x/9 = 20',
    solution:{x:45}, equationCount:1, optimalSteps:2,
    contextAnswer:'45 students total (20 girls, 25 boys). Check: 20:25 = 4:5 ✓' },
  { id:175, tier:4, tierName:'Fractions & Ratios', title:'Marbles removed',
    problem:'A bag has red and blue marbles in ratio 3:2. After removing 4 red marbles, there are equal numbers of red and blue. How many red marbles were there originally?',
    hint:'Let x be the original red count. Blue = 2x/3. After removing 4: x − 4 = 2x/3',
    solution:{x:12}, equationCount:1, optimalSteps:3,
    contextAnswer:'12 red originally (8 blue). Check: 12−4=8=8 ✓ and 12:8 = 3:2 ✓' },

  // ── Tier 5: Challenge (176-185) ──────────────────────────────
  { id:176, tier:5, tierName:'Challenge', title:'Shopkeeper profit',
    problem:'A shopkeeper buys x items at £4 each. He sells 8 fewer than he bought, at £7 each. He makes a profit of £52. How many items did he buy?',
    hint:'Let x be items bought. Revenue = 7(x−8), cost = 4x. Profit: 7(x−8) − 4x = 52',
    solution:{x:36}, equationCount:1, optimalSteps:4,
    contextAnswer:'36 items. Check: 7×28 − 4×36 = 196 − 144 = 52 ✓' },
  { id:177, tier:5, tierName:'Challenge', title:'Tank fill and drain',
    problem:'A tank is filled by a pipe adding 8 litres/min and drained by another removing 3 litres/min. The tank starts with 20 litres. After x minutes it holds 45 litres. Find x.',
    hint:'Let x be the minutes. Net gain = (8−3) per minute. Starting + net gain × time = final: 20 + 5x = 45',
    solution:{x:5}, equationCount:1, optimalSteps:2,
    contextAnswer:'5 minutes. Check: 20 + 5×5 = 20 + 25 = 45 ✓' },
  { id:178, tier:5, tierName:'Challenge', title:'Two towns',
    problem:'A car travels from town A to town B at 60 mph, then returns at 40 mph. The total journey takes 5 hours. Find the distance between the towns.',
    hint:'Let x be the distance. Time = distance ÷ speed. x/60 + x/40 = 5',
    solution:{x:120}, equationCount:1, optimalSteps:3,
    contextAnswer:'120 miles. Check: 120/60 + 120/40 = 2 + 3 = 5 hours ✓' },
  { id:179, tier:5, tierName:'Challenge', title:'Show tickets',
    problem:'Adult tickets cost £x each. Child tickets cost £3 less. A group of 4 adults and 5 children pays £66. Find the adult ticket price.',
    hint:'Let x be the adult price. Child price = x − 3. Total: 4x + 5(x − 3) = 66',
    solution:{x:9}, equationCount:1, optimalSteps:3,
    contextAnswer:'Adult £9, child £6. Check: 4×9 + 5×6 = 36 + 30 = 66 ✓' },
  { id:180, tier:5, tierName:'Challenge', title:'Trains meeting',
    problem:'Two trains start at opposite ends of a 180km track and travel toward each other at 60 km/h and 30 km/h. After how many hours do they meet?',
    hint:'Let x be the hours until they meet. Combined distance = 180: 60x + 30x = 180',
    solution:{x:2}, equationCount:1, optimalSteps:2,
    contextAnswer:'2 hours. Check: 60×2 + 30×2 = 120 + 60 = 180 ✓' },
  { id:181, tier:5, tierName:'Challenge', title:'Simple interest',
    problem:'You invest £x at 5% simple interest per year. After 2 years your total is £3300. Find the original investment.',
    hint:'Let x be the investment. Interest = 0.05x per year. Total after 2 years: x + 2×0.05x = 3300',
    solution:{x:3000}, equationCount:1, optimalSteps:3,
    contextAnswer:'£3000. Check: 3000 + 2×150 = 3000 + 300 = 3300 ✓' },
  { id:182, tier:5, tierName:'Challenge', title:'Sale then rise',
    problem:'A shop reduces prices by 30% in a sale. Later, prices rise 20% from the sale price. The final price is £168. What was the original price?',
    hint:'Let x be the original price. After 30% off: 0.7x. After 20% rise: 0.7x × 1.2 = 168',
    solution:{x:200}, equationCount:1, optimalSteps:3,
    contextAnswer:'£200. Check: 200 × 0.7 = 140, 140 × 1.2 = 168 ✓' },
  { id:183, tier:5, tierName:'Challenge', title:'Two exams',
    problem:'A class of 35 students sits two exams. 20 pass the first, 25 pass the second, and every student passes at least one. How many students pass both exams?',
    hint:'Let x be the students who pass both. By inclusion-exclusion: 20 + 25 − x = 35',
    solution:{x:10}, equationCount:1, optimalSteps:2,
    contextAnswer:'10 students pass both. Check: 20 + 25 − 10 = 35 ✓' },
  { id:184, tier:5, tierName:'Challenge', title:'Number and expression',
    problem:'A number is added to three times the result of subtracting 4 from that number. The answer is 36. Find the number.',
    hint:'Let x be the number. "Three times (x−4)" is 3(x−4). So x + 3(x − 4) = 36',
    solution:{x:12}, equationCount:1, optimalSteps:3,
    contextAnswer:'12. Check: 12 + 3×(12−4) = 12 + 24 = 36 ✓' },
  { id:185, tier:5, tierName:'Challenge', title:'Pay rises',
    problem:'A worker\'s hourly rate increases by 20%, then gets a further 10% bonus on the new rate. The effective rate is £39.60. Find the original hourly rate.',
    hint:'Let x be the original rate. After 20% rise: 1.2x. After 10% bonus: 1.2x × 1.1 = 39.60',
    solution:{x:30}, equationCount:1, optimalSteps:3,
    contextAnswer:'£30/hr. Check: 30 × 1.2 × 1.1 = 30 × 1.32 = 39.60 ✓' },

  // ── Tier 6: Word Systems I (186-193) ─────────────────────────
  { id:186, tier:6, tierName:'Word Systems I', title:'Café order',
    problem:'2 lattes and 3 cappuccinos cost £19. A latte costs £2 more than a cappuccino. Find the price of each.',
    hint:'Let x be latte price, y be cappuccino price. Write two equations: 2x + 3y = 19 and x = y + 2',
    solution:{x:5,y:3}, equationCount:2, optimalSteps:4,
    contextAnswer:'Latte £5, cappuccino £3. Check: 2×5 + 3×3 = 10+9 = 19 ✓ and 5−3=2 ✓' },
  { id:187, tier:6, tierName:'Word Systems I', title:'Trains toward each other',
    problem:'Two trains start from opposite ends of a 180km track and travel toward each other. The faster train goes 20 km/h faster. They meet after 2 hours. Find each train\'s speed.',
    hint:'Let x be the fast speed, y the slow speed. Distance covered: 2x + 2y = 180 and x = y + 20',
    solution:{x:55,y:35}, equationCount:2, optimalSteps:4,
    contextAnswer:'Fast: 55 km/h, slow: 35 km/h. Check: 2×55+2×35=180 ✓ and 55−35=20 ✓' },
  { id:188, tier:6, tierName:'Word Systems I', title:'Sharing marbles',
    problem:'Ali and Ben have 40 marbles in total. If Ali gives 5 to Ben, they have equal amounts. How many does each have?',
    hint:'Let x be Ali\'s count, y be Ben\'s. Write: x + y = 40 and x − 5 = y + 5',
    solution:{x:25,y:15}, equationCount:2, optimalSteps:4,
    contextAnswer:'Ali has 25, Ben has 15. Check: 25+15=40 ✓ and 25−5=20=15+5 ✓' },
  { id:189, tier:6, tierName:'Word Systems I', title:'Chickens and cows',
    problem:'A farmer has chickens and cows. There are 30 heads and 86 legs in total. How many of each animal are there?',
    hint:'Let x be chickens, y be cows. Heads: x + y = 30. Legs: 2x + 4y = 86',
    solution:{x:17,y:13}, equationCount:2, optimalSteps:5,
    contextAnswer:'17 chickens and 13 cows. Check: 17+13=30 ✓ and 34+52=86 ✓' },
  { id:190, tier:6, tierName:'Word Systems I', title:'Mother and son ages',
    problem:'Two years ago, a mother was 3 times as old as her son. Now their ages sum to 40. How old are they now?',
    hint:'Let x be mother\'s age now, y be son\'s age now. x + y = 40 and (x−2) = 3(y−2)',
    solution:{x:29,y:11}, equationCount:2, optimalSteps:5,
    contextAnswer:'Mother 29, son 11. Check: 29+11=40 ✓ and 27=3×9 ✓' },
  { id:191, tier:6, tierName:'Word Systems I', title:'Two hotels',
    problem:'Three nights at Hotel A plus two nights at Hotel B costs £350. Two nights at Hotel A plus three nights at Hotel B costs £300. Find each nightly rate.',
    hint:'Let x be Hotel A\'s rate, y be Hotel B\'s. 3x + 2y = 350 and 2x + 3y = 300',
    solution:{x:90,y:40}, equationCount:2, optimalSteps:5,
    contextAnswer:'Hotel A £90/night, Hotel B £40/night. Check: 3×90+2×40=270+80=350 ✓' },
  { id:192, tier:6, tierName:'Word Systems I', title:'Parking meter',
    problem:'A parking meter charges £x for the first hour and £y for each additional hour. 3 hours costs £8 and 5 hours costs £14. Find x and y.',
    hint:'Let x be first-hour charge, y be additional-hour charge. x + 2y = 8 and x + 4y = 14',
    solution:{x:2,y:3}, equationCount:2, optimalSteps:4,
    contextAnswer:'First hour £2, additional hours £3 each. Check: 2+2×3=8 ✓ and 2+4×3=14 ✓' },
  { id:193, tier:6, tierName:'Word Systems I', title:'Rectangle from perimeter',
    problem:'A rectangle\'s perimeter is 56cm. Its length is 3 times its width minus 4cm. Find both dimensions.',
    hint:'Let x be the length, y be the width. 2x + 2y = 56 and x = 3y − 4',
    solution:{x:20,y:8}, equationCount:2, optimalSteps:5,
    contextAnswer:'Length 20cm, width 8cm. Check: 2×20+2×8=56 ✓ and 20=3×8−4=20 ✓' },

  // ── Tier 7: Word Systems II (194-200) ────────────────────────
  { id:194, tier:7, tierName:'Word Systems II', title:'River current',
    problem:'A motorboat travels 36km downstream in 2 hours and 36km upstream in 3 hours. Find the boat\'s speed in still water and the river current speed.',
    hint:'Let x be the boat\'s speed, y be the current. Downstream: x+y=18. Upstream: x−y=12',
    solution:{x:15,y:3}, equationCount:2, optimalSteps:6,
    contextAnswer:'Boat: 15 km/h, current: 3 km/h. Check: 15+3=18 ✓ and 15−3=12 ✓' },
  { id:195, tier:7, tierName:'Word Systems II', title:'Two savings accounts',
    problem:'You split £1000 between two accounts. Account A pays 4% interest, Account B pays 6%. After one year you earn £54 in total interest. How much is in each account?',
    hint:'Let x be amount in A, y in B. x + y = 1000 and 0.04x + 0.06y = 54',
    solution:{x:300,y:700}, equationCount:2, optimalSteps:6,
    contextAnswer:'£300 in A, £700 in B. Check: 0.04×300+0.06×700=12+42=54 ✓' },
  { id:196, tier:7, tierName:'Word Systems II', title:'Two workers\' pay',
    problem:'Two workers do 6 hours each. Together they earn £84. One earns £4/hr more than the other. Find each hourly rate.',
    hint:'Let x be the higher rate, y the lower. 6x + 6y = 84 and x − y = 4',
    solution:{x:9,y:5}, equationCount:2, optimalSteps:5,
    contextAnswer:'£9/hr and £5/hr. Check: 6×9+6×5=54+30=84 ✓ and 9−5=4 ✓' },
  { id:197, tier:7, tierName:'Word Systems II', title:'Plane and headwind',
    problem:'A plane flies 2000km with a tailwind in 4 hours. Against the same wind the same distance takes 5 hours. Find the plane\'s airspeed and the wind speed.',
    hint:'Let x be airspeed, y be wind speed. With wind: x+y=500. Against wind: x−y=400',
    solution:{x:450,y:50}, equationCount:2, optimalSteps:5,
    contextAnswer:'Airspeed 450 km/h, wind 50 km/h. Check: 450+50=500 ✓ and 450−50=400 ✓' },
  { id:198, tier:7, tierName:'Word Systems II', title:'Pizza prices',
    problem:'3 small pizzas and 2 large pizzas cost £37. 2 small and 3 large cost £38. Find the price of each size.',
    hint:'Let x be small pizza price, y be large. 3x + 2y = 37 and 2x + 3y = 38',
    solution:{x:7,y:8}, equationCount:2, optimalSteps:6,
    contextAnswer:'Small £7, large £8. Check: 3×7+2×8=21+16=37 ✓ and 2×7+3×8=14+24=38 ✓' },
  { id:199, tier:7, tierName:'Word Systems II', title:'Student scores',
    problem:'Student A scored 4 more than twice Student B\'s score. Their total score is 55. Find each student\'s score.',
    hint:'Let x be A\'s score, y be B\'s. x + y = 55 and x = 2y + 4',
    solution:{x:38,y:17}, equationCount:2, optimalSteps:5,
    contextAnswer:'A scored 38, B scored 17. Check: 38+17=55 ✓ and 38=2×17+4=38 ✓' },
  { id:200, tier:7, tierName:'Word Systems II', title:'Factory profit',
    problem:'A factory makes tables and chairs. 5 tables and 8 chairs yield £136 profit. 3 tables and 4 chairs yield £72 profit. Find the profit per table and per chair.',
    hint:'Let x be profit per table, y per chair. 5x + 8y = 136 and 3x + 4y = 72',
    solution:{x:8,y:12}, equationCount:2, optimalSteps:6,
    contextAnswer:'Table £8, chair £12 profit each. Check: 5×8+8×12=40+96=136 ✓ and 3×8+4×12=24+48=72 ✓' },
];
